### ISSUE TITLE
failed to download latest wasm-tools release

### ISSUE THREAD

**Issue by thomasheyenbrock** [fastly/cli#1072]
**Version**

10.6.0

**What happened**

Running `fastly build` in CI resulted in the following error:

```
/opt/hostedtoolcache/fastly/10.6.0/x64/fastly compute build --non-interactive
| Verifying fastly.toml...
/ Verifying fastly.toml...
✓ Verifying fastly.toml
| Fetching latest wasm-tools release...
/ Fetching latest wasm-tools release...
✗ Fetching latest wasm-tools release

ERROR: failed to download latest wasm-tools release: failed to request GitHub release asset: Get "": unsupported protocol scheme "".
```

We didn't change anything and it all worked earlier today, might this be a bug with the new CLI version?

**Comment by Integralist** [comment]
Hi @thomasheyenbrock 

Thanks for opening this issue.

I'm investigating and will report back as soon as I can.

**Comment by Integralist** [comment]
@thomasheyenbrock looks like the wasm-tools repository doesn't use a standardised convention for naming their downloadable assets so we've got a workaround in place (see linked PR).

**Comment by Integralist** [comment]
The new [`v10.6.1`](https://github.com/fastly/cli/releases/tag/v10.6.1) patch release should hopefully help resolve this. Let us know if there are still problems.

Thanks!

**Comment by thomasheyenbrock** [comment]
Works again, thanks for the quick fix!
