### ISSUE TITLE
404 Not Found: Record not found when deleting config store via Fastly CLI

### ISSUE THREAD

**Issue by alex8bitw** [fastly/cli#1123]
**Version**

Fastly CLI version v10.8.0 (8b3c0372)
Built with go version go1.21.5 linux/amd64 (2024-01-23)
Viceroy version: viceroy 0.9.3

**What happened**

```
fastly config-store list
Name                                                        ID                     Created (UTC)    Updated (UTC)
XXXXXXX                            gD4U3AfZko2bpmidpckkb2  2024-01-23 09:04  2024-01-23 09:04
```

```
fastly  config-store describe -s gD4U3AfZko2bpmidpckkb2
Name: XXXXXXX
ID: gD4U3AfZko2bpmidpckkb2
Created (UTC): 2024-01-23 09:04
Updated (UTC): 2024-01-23 09:04
```

```
 fastly config-store delete --store-id=gD4U3AfZko2bpmidpckkb2

ERROR: the Fastly API returned 404 Not Found: Record not found.
```

**Comment by Integralist** [comment]
👋🏻 

Thanks for taking the time to open this issue.

Unfortunately, I'm unable to replicate the problem using the same version of the Fastly CLI.

So this doesn't appear to be a CLI-specific issue. 

I would strongly recommend reaching out to https://support.fastly.com/ and opening a support ticket as they'll be able to inspect your account configuration to ensure everything is setup correctly and with the correct permissions.

Thanks.
