### ISSUE TITLE
Unable to change account when creating sso profiles

### ISSUE THREAD

**Issue by Meroje** [fastly/cli#1152]
**Version**

Fastly CLI version v10.8.5 (d451b709)
Built with go version go1.22.0 linux/amd64 (2024-03-11)

**What happened**

I have multiple fastly accounts that I want to setup an SSO profile for.
I run `fastly profile create bar --sso` then `fastly profile create foo --sso`. Both profiles are setup to the same account because the second command did not get a prompt to confirm the account. Instead it implicitly accepted my current browser session and redirected to the "Authenticated successfully. Please close this page and return to the Fastly CLI in your terminal." page.

**Comment by Integralist** [comment]
Thanks @Meroje for opening this issue. We are aware of this issue and are actively tracking it internally. We'll be sure to update this GitHub issue once a resolution has been implemented.

**Comment by kpfleming** [comment]
There have been a number of SSO and profile related changes in the most recent releases; could you re-test the scenario above and see if there is still a problem? Thanks.

**Comment by Integralist** [comment]
👋🏻 

I believe this issue to be resolved with the latest CLI release so I'll close this issue.

@Meroje if you run into any problems, then please either open a new issue or re-open this one if the error is still relevant.

Thanks!
