### ISSUE TITLE
Allow setting/updating the logfile field of Scalyr endpoints

### ISSUE THREAD

**Issue by cee-dub** [fastly/cli#1165]
**Is your feature request related to a problem? Please describe.**
There's a UI feature to change the logfile name sent to Scalyr, but it isn't exposed in the CLI.

**Describe the solution you'd like**
I have opened [a PR against https://github.com/fastly/go-fastly](https://github.com/fastly/go-fastly/pull/508) to expose the API field used by the UI. The CLI needs to be updated to match.

**Describe alternatives you've considered**
Not using this field. Having my app log its own field instead.

**Additional context**
<img width="635" alt="Screenshot 2024-03-14 at 13 18 56" src="https://github.com/fastly/cli/assets/1292/ef97e667-c96a-40e8-af2a-c7d424697bbd">

**Comment by kpfleming** [comment]
This was completed in #1166.
