### ISSUE TITLE
--file option of fastly compute serve looks like it's ignored

### ISSUE THREAD

**Issue by jedisct1** [fastly/cli#1198]
**Version**

36a4ce4da8c1333f93523711852a15b3073db443

**What happened**

```sh
$ fastly compute serve --file=zig-out/bin/package.wasm

ERROR: error creating package archive: error copying file: cannot read source file: ./bin/main.wasm.
```

This is confusing and feels like the `--file` option is ignored and `./bin/main.wasm` is hard-coded.

It works if the `--skip-build` option is also present, though.

**Comment by Integralist** [comment]
This looks like a bug.

https://github.com/fastly/cli/blob/main/pkg%2Fcommands%2Fcompute%2Fbuild.go#L295

It references a constant when it should use the flag value.

The workaround, as you've noted, is to skip the build entirely.

I'll work on a fix tomorrow.

**Comment by jedisct1** [comment]
Awesome, thank you!
