### ISSUE TITLE
ERROR: failed to configure authentication processes: failed to unmarshal OpenID Connect .well-known metadata: invalid character 'I' looking for beginning of value

### ISSUE THREAD

**Issue by marceloboeira** [fastly/cli#1210]
**Version**

```
Fastly CLI version v10.8.0 (8b3c0372)
Built with go version go1.21.5 linux/amd64 (2024-05-21)
Viceroy version: viceroy 0.9.3

A new version of the Fastly CLI is available.
Current version: 10.8.0
```

**What happened**

We have a pipeline, that hasn't changed in a while, with this command:  
```sh
fastly compute publish --verbose
```

It normally publishes the application to compute @ edge, now it started failing with:

```
ERROR: failed to configure authentication processes: failed to unmarshal OpenID Connect .well-known metadata: invalid character 'I' looking for beginning of value.
```

Note: It seems to be related to https://www.fastlystatus.com/incident/376536, I'm guessing the `invalid character 'I' looking for beginning of value` is for `Internal Server Error` but thought of reporting it here should other people face it too.

**Comment by Integralist** [comment]
Hi @marceloboeira 

You're correct, there was an incident that appears to have caused an issue wit the OICD endpoint used by the CLI (I myself just ran into this). The endpoint is back up already but I'll leave this issue open for now until I get a confirmation that the underlying issue is confirmed resolved.

**Comment by marceloboeira** [comment]
@Integralist looking good now! I'm wondering if that's an opportunity to catch that type of error and improve the message (e.g.: if a 5xx is returned then switch the message to "An unexpected authentication error occurred, check http://fastlystatus.com for any possible incidents" and then some debug details (e.g.: statuscode/body)).

Happy to work on an MR for that if the behaviour is desired. 

In any case, I'll close this issue since the original problem is resolved.

**Comment by Integralist** [comment]
Hi @marceloboeira 

> I'm wondering if that's an opportunity to catch that type of error and improve the message
> Happy to work on an MR for that if the behaviour is desired.

Yes please! That would be very much appreciated 🙂 🙇🏻
