### ISSUE TITLE
FASTLY API - 404 Not found error

### ISSUE THREAD

**Issue by alejandrto** [fastly/cli#1237]
**Version**

Please paste the output of `fastly version` here.
Fastly CLI version v10.10.0 (73ec7c76)
Built with go version go1.22.3 linux/amd64 (2024-07-03)
Viceroy version: viceroy 0.9.6

A new version of the Fastly CLI is available.
Current version: 10.10.0
Latest version: 10.12.3
Run `fastly update` to get the latest version.

**What happened**

Please describe the command you ran, what you expected to happen, and what happened instead.

ran fastly compute build 

then ran fastly compute deploy                                    
✓ Verifying fastly.toml

A new version of the Fastly CLI is available.
Current version: 10.10.0
Latest version: 10.12.3
Run `fastly update` to get the latest version.

ERROR: the Fastly API returned 404 Not Found: Not found.

Also ran fastly compute publish --service-id=5plWLRgIQuZP8slgmZWFc3
✓ Verifying fastly.toml
✓ Identifying package name
✓ Identifying toolchain
✓ Running [scripts.build]
✓ Creating package archive

SUCCESS: Built package (pkg/fastly-edge-test-application.tar.gz)

✓ Verifying fastly.toml

A new version of the Fastly CLI is available.
Current version: 10.10.0
Latest version: 10.12.3
Run `fastly update` to get the latest version.

ERROR: the Fastly API returned 404 Not Found: Not found.

we updated the version and still ran into the same issue

**Comment by kpfleming** [comment]
For additional debugging, you can run the command prefixed with `FASTLY_DEBUG_MODE=true` which will provide more details about what the CLI was doing when the failure occurred.

**Comment by kpfleming** [comment]
Closing due to lack of response; if this is still an issue for you feel free to reopen it and provide the requested information.
