### ISSUE TITLE
deploying a rust application

### ISSUE THREAD

**Issue by alejandrto** [fastly/cli#1256]
I am attempting to deploy a **rust** application and I can build successfully, but have issues with deployment/publishing the service. Unsure why I just get a 404 Not found error with Fastly

**output of `fastly version`:**
fastly 
version
Fastly CLI version v10.12.3 (f0fe32f4)
Built with go version go1.22.4 linux/amd64 (2024-07-29)
Viceroy version: viceroy 0.10.2

****I ran: FASTLY_DEBUG_MODE=true fastly compute deploy**
Result:**

✓ Verifying fastly.toml

http.Request (dump): "GET /service/rotR247Rh33bN7kTqgy0T0/version HTTP/1.1\r\nHost: api.fastly.com\r\nUser-Agent: FastlyCLI/v10.12.3, FastlyGo/9.5.0 (+github.com/fastly/go-fastly; go1.22.4)\r\n\r\n"
http.Response (dump): "HTTP/2.0 404 Not Found\r\nAccept-Ranges: bytes\r\nAge: 0\r\nCache-Control: no-store\r\nContent-Type: application/json\r\nDate: Mon, 29 Jul 2024 18:01:29 GMT\r\nPragma: no-cache\r\nServer: control-gateway\r\nStatus: 404 Not Found\r\nStrict-Transport-Security: max-age=31536000\r\nVary: Accept-Encoding\r\nVia: 1.1 varnish, 1.1 varnish\r\nX-Cache: MISS, MISS\r\nX-Cache-Hits: 0, 0\r\nX-Served-By: cache-chi-kigq8000058-CHI, cache-pdk-kpdk1780082-PDK\r\nX-Timer: S1722276090.566775,VS0,VE66\r\n\r\n"

**ERROR: the Fastly API returned 404 Not Found: Not found.**

**Comment by kpfleming** [comment]
Does the Fastly API token that you are using have any restrictions? For example, is it restricted to only managing some specific service(s)?

**Comment by alejandrto** [comment]
Yes that was the issue! I had to specify another api token in order to publish. I did not have an issue before when I deployed with javascript, but maybe the settings changed
