### ISSUE TITLE
[BUG] accidental service deletion when PR is cleaned up for failed deployment

### ISSUE THREAD

**Issue by NeilHanlon** [fastly/cli#1261]
**Version**

```
Fastly CLI version v10.12.3 (f0fe32f4)
Built with go version go1.22.4 linux/amd64 (2024-07-30)
```

**What happened**

**Command Ran:**
```bash
fastly service delete --quiet --service-name @resf/rocky-linux-docs-73 --force --token ***
```

**Expected:**
I expected the service identified by the `--service-name` argument to be deleted.

**Actual:**
Despite providing `--service-name`, the `fastly service delete` command deleted the service ID specified in the `fastly.toml`. This led to the accidental deletion of the main service instead of the intended preview service.

**Possible Fixes:**
1. Modify the Fastly CLI to verify the named service existence before attempting deletion.
2. Modify the Fastly CLI to raise an error if inconsistent instructions are given (i.e., `--service-name` should never fall back to a stored value).

ref: https://github.com/fastly/compute-actions/issues/52

**Comment by kpfleming** [comment]
Ouch! Thanks for the detailed bug report. I'll begin looking into this ASAP.

**Comment by NeilHanlon** [comment]
It's alright, bugs happen! Thankfully it was straightforward to repair :)

re-reading my PR, it's not obvious, but the service name '@resf/rocky-linux-docs-73' never existed, it kept failing to deploy so I just force merged the branch to main ;)

**Comment by kpfleming** [comment]
I've done a code review and confirmed exactly how this happened, that's progress.

**Comment by kpfleming** [comment]
This will be included in a new release of the CLI early next week.

**Comment by NeilHanlon** [comment]
Thank you!
