### ISSUE TITLE
rustc 1.80 regression: type annotations needed for Box<_>

### ISSUE THREAD

**Issue by SachaMorard** [fastly/cli#1263]
**Version**

Fastly CLI version v10.12.3 (f0fe32f4)
Built with go version go1.22.4 linux/amd64 (2024-08-01)
Viceroy version: viceroy 0.10.2

**What happened**

I updated rustup to the last stable version (1.80) and I'm not able to build my fastly compute apps anymore, because of the `time` dependency.

Here the error I have:

```bash
error[E0282]: type annotations needed for `Box<_>`
  --> /myapp/vendor/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

Unfortunately, it seems impossible to bump the `time` package version.

**Comment by kpfleming** [comment]
This is not actually a bug in the CLI, it's a bug in our Rust SDK, and we expect to be publishing a new version shortly (possibly even today). For the moment the workaround is go back to Rust 1.79.0 until the new SDK version has been published.

**Comment by SachaMorard** [comment]
Thank you @kpfleming 
How can I post a problem for your Rust SDK? I've looked everywhere, but there doesn't seem to be any public access.

**Comment by kpfleming** [comment]
That is correct, unfortunately there is no public issue tracker for the Rust SDK.
