### ISSUE TITLE
API connection fails on `fastly profile create` on termux

### ISSUE THREAD

**Issue by pufferfish101007** [fastly/cli#1267]
**Version**

Fastly CLI version v10.1.0 (4ffcd8d5)
Built with go version go1.20.4 linux/amd64

**What happened**

I have installed the Fastly CLI on termux (a terminal emulator for android) via the `linux-arm64` build on the releases page. It seems to work fine inasmuch that basic commands (version, help) work. When providing a token to `fastly profile create`, I get the following error:
```
✗ Validating token

ERROR: error validating token: Get "https://api.fastly.com/tokens/self": dial tcp: lookup api.fastly.com on [::1]:53: read udp [::1]:46178->[::1]:53: read: connection refused.
```
As far as I'm aware the token was correct, and the error doesn't sound like it's to do with an incorrect token. My network is not experiencing any issues and trying again doesn't make a difference.
I have no idea where to even start figuring out what's going on and a quick google search doesn't reveal anything useful.
Thanks in advance for any support.

**Comment by kpfleming** [comment]
Based on that output the Golang `net/http` library was trying to do a DNS lookup so it could get an IP address for `api.fastly.com`. If the environment where you are trying to run the CLI has an `/etc/resolv.conf` or something similar pointing to "[::1]" but doesn't actually have a resolver listening there then this will fail.

**Comment by pufferfish101007** [comment]
Thanks for your response. I believe that on my system, `resolv.conf` exists at `/usr/etc/resolv.conf` rather than `/etc/resolv.conf`, and `/etc` is read-only (my phone is non-rooted). It appears that this is more of an issue with Golang & termux than with the fastly CLI, so I'll close this.
Thank you for pointing me in the right direction!
