### ISSUE TITLE
cannot install exe file on Windows why ???😡

### ISSUE THREAD

**Issue by ikiizz** [fastly/cli#1279]
**Version**

-

**What happened**

After extract zip file, fastly cli for windows amd64, i click fastly exe, the exe file is open shortly and then close, please answer this !!

**Comment by Integralist** [comment]
👋

The Fastly executable needs to be run within a terminal shell. What shell are you using and what command are you running?

For example, once you have extracted the exe and placed it in your PATH, you should be able to run the following command:

```
fastly help
```

The above command will display all available subcommands.

**Comment by ikiizz** [comment]
Ok, thanks for your answer.
