### ISSUE TITLE
found ip address signing into my xfinity account just days ago

### ISSUE THREAD

**Issue by jrichy1** [fastly/cli#1280]
146.75.244.0

`this ip was found in my recent logins on my xfinity account yeah i use your services but not once did i authorize you guys to be signing into my accounts especially my internet account if this happens agin i will report it`

![IMG_0737](https://github.com/user-attachments/assets/db61a7f2-eab6-4833-b1d8-cac7fd3fd71e)

**Comment by Integralist** [comment]
👋

I don't know of any reason Fastly would (or could, from it's platform) log into your xfinity account. 

That said, I would recommend reaching out to the Fastly support team at https://support.fastly.com/ as this repository is for issues related to the Fastly CLI.
