### ISSUE TITLE
Unable to Use Local Project Template

### ISSUE THREAD

**Issue by peterhriser** [fastly/cli#1318]
**Version**

Please paste the output of `fastly version` here.

```
Fastly CLI version v10.13.3 (d6bdae2c)
Built with go version go1.22.6 linux/amd64 (2024-09-17)
Viceroy version: viceroy 0.12.0
```

**What happened**

When trying to run `fastly compute init --from="../../compute-start-kit-rust-empty"`, it fail with error like: 

```
ERROR: --from url seems invalid: ../../compute-start-kit-rust-empty # this is the github repo cloned locally
```

This seems to be incongruent with the description of `--from` flag which states
```
  -f, --from=FROM     Local project directory, or Git repository URL,
                             or URL referencing a .zip/.tar.gz file, containing
                             a package template, or an existing service ID
```
 
I saw in documentation that it needs to be language aware potentially so I used the following flags to same result:

```
fastly compute init -i  -y  -l rust -d --from="../../compute-start-kit-rust-empty"
```

Finally I also have used `file://` in hopes that would work to no avail. Poking around the repo, I do not see too much reference to local project templates so potentially the flag description is incorrect?

**Comment by kpfleming** [comment]
The code does indeed support a local directory path for `--from`. I've tried this on my Linux system (using CLI 10.14.0 and 10.14.1), with a relative path to the same starter kit, both with and without quotes, and it worked correctly in both cases.

Are you running the commands on Linux, macOS, or Windows? If you can reproduce this with 10.14.1, we'll need to do some more investigation.

**Comment by peterhriser** [comment]
@kpfleming I am using macOS Sonoma 14.6.1. I am somewhat new to fastly so may be user error on my side but I tried a few permutations to no avail but only on one device.

Just tested with updated CLI

```
❯ fastly version
Fastly CLI version v10.14.1 (b3926881)
Built with go version go1.22.7 linux/amd64 (2024-09-23)
Viceroy version: viceroy 0.12.0
❯ 
❯ fastly compute init -i  -y  -l rust -d --from=./compute-start-kit-rust-empty
Creating a new Compute project (using --from to locate package template).

Press ^C at any time to quit.

✓ Validating directory permissions

✗ Fetching package template

ERROR: --from url seems invalid: ./compute-start-kit-rust-empty.
```
  
Tried the above with a few iterations of different flags as well to eliminate that as well.

**Comment by kpfleming** [comment]
The path you supplied is to a subdirectory of your current directory, which would cause problems if the CLI actually tried to use it. If you would, please provide the outputs of these commands:

```
pwd

ls

ls (path to compute-start-kit-rust-empty)
```

Also it may be relevant that if you'd previously used `git clone` to clone the starter kit and let it create the directory, you've misspelled the directory name ('start' -> 'starter').

**Comment by kpfleming** [comment]
If the path you are providing is to a valid starter kit, you do not need any of the additional flags, `--from` will be sufficient.

**Comment by peterhriser** [comment]
spelling correctly did not work but fully removing and re-installing the CLI did. I'm not sure what the issue was but it seems to have been resolved by that. Thank you for the help!
