### ISSUE TITLE
fastlyctl migration to fastly cli

### ISSUE THREAD

**Issue by kmcrawford** [fastly/cli#1348]
I would like to migrate from fastlyctl, but my main usage of fastlyctl is not supported by fastly cli.

I keep my VCL code in my private github repo, make changes in my editor and use 
`fastlyctl upload`
Then `fastlyctl activate --c "JIRA-1817 commit message"` 

Is there a secret fastlyctl cli command that I can't find that works the same way?

**Comment by kpfleming** [comment]
I believe the 'fastly vcl custom ...' [family of commands](https://www.fastly.com/documentation/reference/cli/vcl/custom/) are what you are looking for.

**Comment by kmcrawford** [comment]
These commands look like they are intended to update 1 vcl at a time.  With `fastlyctl upload` it will do a diff of all VCLs in my local and compare what should be uploaded.

**Comment by kpfleming** [comment]
Ahhh, then no, there is no equivalent commands in the Fastly CLI that I'm aware of.

**Comment by kmcrawford** [comment]
bummer.. I see this message nearly every day, it would be nice to migrate:
```
DEPRECATED: FastlyCTL is no longer maintained or supported.  Many features are already available in the official Fastly CLI (https://github.com/fastly/cli), which is actively maintained and developed.  Please consider migrating if possible.
```

**Comment by kpfleming** [comment]
Fair enough. While it would be a big lift, it seems that using Terraform and the Fastly Terraform provider would give you a similar result. The TF configuration would have resource definitions for each of the Delivery services you are managing, and those definitions would contain `vcl` blocks which point to the VCL source files on your filesystem. A `terraform plan` operation would compare the current VCLs in the services to the ones on your filesystem, indicate which ones will need to be uploaded, and then a `terraform apply` would take those actions.
