### ISSUE TITLE
Multiple switchable profiles

### ISSUE THREAD

**Issue by jregistr** [fastly/cli#142]
👋  Hellos!

I created this issue https://github.com/fastly/cli/issues/141 earlier sharing some thoughts. I wanted to ask if y'all have anything in mind or planned for folks using multiple API Keys and Service IDs.
I'm currently taking care of this with some functions in my bash profile, like so:
```bash
dev() {
  export FASTLY_API_KEY = '...'
  export FASTLY_SVC_ID = '...'
}
stg () {......}
```

In a way, this is similar to "profiles" on the AWS CLI.

So I could see something like a `$HOME/.config/fastly.toml` config containing these.

That being said, I understand this tool is quite new, and this probably something way at the back of the roadmap or even thoughts.

**Comment by StarpTech** [comment]
Hi, what's the status? I also have multiple accounts and it would be great to deal with them as with multiple was accounts. This is very basic functionality.

**Comment by Integralist** [comment]
Hi @jregistr thanks for raising this issue, and thanks @StarpTech for popping in to check for a status update!

So we're currently in the process of evolving the authentication model used by the CLI. Once that work is complete (worst case in a couple of weeks), then we can start looking into supporting multiple profiles. 

We already have an internal ticket related to this work, but it has not yet been prioritised. That said, there's been interest both internally and externally for this feature so I could see this getting scheduled maybe in the next quarter. 

Unfortunately I can't guarantee that will happen at this stage, but we are aware of this feature as being an important one for our users so it's a likely next candidate following the CLI's authentication model update.

**Comment by Integralist** [comment]
👋🏻 @StarpTech 

I've managed to get the ball rolling on multiple profiles: https://github.com/fastly/cli/pull/546

I've more work to do on this, and it's very much a WIP, but in case you were interested in an update 🙂

**Comment by Integralist** [comment]
The PR to add profiles (https://github.com/fastly/cli/pull/546) has been approved, but isn't yet merged. 

@StarpTech if you had any opinions on the change of interface, now would be the time to comment in the PR comments 🙂
