### ISSUE TITLE
Support more than one Rust toolchain version

### ISSUE THREAD

**Issue by phamann** [fastly/cli#157]
Currently we force a single Rust toolchain version when compiling Rust based Compute@Edge programs via `fastly compute build`. Ideally we should support a SemVer range (minimum -> maximum) to be more flexible for user and CI toolchain environments.

**Comment by pchickey** [comment]
Ideally we would always support the `stable` rust version - this special version points to the latest stable release that rustup knows about. So maybe we should express a disjunction of constaints?
