### ISSUE TITLE
Support alternative languages / precompiled modules

### ISSUE THREAD

**Issue by jedisct1** [fastly/cli#174]
C@E can run modules written in any language that can compile to WebAssembly.

However, the CLI tool assumes that only Rust or AssemblyScript can be used, which [complicates deployment for modules written in other languages](https://github.com/jedisct1/zigly#deployment-to-fastlys-platform).

Would it be reasonable to:
- Add an `other` choice to the list of languages when initializing a new local package (the `build` command would then be an error or a no-op)
- Add a `fastly compute package` that accepts a path to an existing module, and would just copy it to the `pkg` directory and bump the version?

That would be wonderful!

Thanks!

**Comment by Integralist** [comment]
👋🏻 There's a draft PR in the works here https://github.com/fastly/cli/pull/282
