### ISSUE TITLE
Documentation typo in `fastly service-version update`

### ISSUE THREAD

**Issue by csilvers** [fastly/cli#22]
**Version**

Fastly CLI version 0.5.1-rc1 (aff2e60)
Built with go version go1.14.2 linux/amd64

**What happened**

`fastly service-version update --help`:
```
[...]
REQUIRED FLAGS
  --version=VERSION  Number of version you wish to clone
  --comment=COMMENT  Human-readable comment
[...]
```
I assume it should say "version you wish to update", rather than "clone".

**Comment by phamann** [comment]
Thank you for finding and reporting this @csilvers, I have fixed in #31
