### ISSUE TITLE
fastly compute build exits with error 1

### ISSUE THREAD

**Issue by andersjanmyr** [fastly/cli#227]
**Version**

Fastly CLI version 0.26.1 (2c06239)
Built with go version unknown

**What happened**

```
$ fastly -v compute build
Fastly API token provided via FASTLY_API_TOKEN
Fastly API endpoint: https://api.fastly.com
Verifying package manifest...
Verifying local rust toolchain...
Checking if rustup is installed...
Found rustup at /Users/anjan9/.cargo/bin/rustup
Checking if Rust  is installed...
Checking if  target is installed...

ERROR: error executing rustup: exit status 1.
```
This has happened on and off since version 23 or something when the `manifest_version` was introduced.

```
authors = ["xxx"]
description = "xxx x Test"
language = "rust"
manifest_version = 1
version = 1
name = "xxx"
service_id = "xxx"
```

**Comment by andersjanmyr** [comment]
It's working again. After moving back to `0.24.2` and then running `fastly compute build`. It now works with `0.26.2`.

**Comment by Integralist** [comment]
Thanks @andersjanmyr we're also going to be implementing some extra error handling to try and shake-out this issue.
