### ISSUE TITLE
Add new subcommand to build and deploy a C@E service

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#232]
Add a `publish` subcommand to `fastly compute` to build and deploy a service. 
This was mentioned recently in two separate conversations.

After this change, `fastly compute publish` always builds. 
If you use `fastly compute deploy` and have local changes, they will be ignored (existing behaviour).

**Comment by Integralist** [comment]
@fgsch I'm presuming the flags that are defined for build/deploy will not be taken into consideration when running `fastly compute publish`, otherwise those flags would have to be aggregated into the `publish` subcommand for it to be able to pass the data down into the `build`/`deploy` functions.

**Comment by fgsch** [comment]
My suggestion is to keep the flags for `deploy`, they seem to be useful for publishing as well, and perhaps also include `--include-source`. The rest of the `build` flags won't be missed, I believe.

**Comment by fgsch** [comment]
My argument against merging both flags is that if you really need to use most (all?) of them, you are better off running build and deploy separately.  

Also it's easier to add flags when needed than removing flags nobody uses, so I'm sticking to my comments in https://github.com/fastly/cli/issues/232#issuecomment-811031932.

**Comment by Integralist** [comment]
Agreed it's easier to add flags than remove those no-one needs but the fact is we don't necessarily know what people are going to want to use and as we're already suggesting implementing half of the available flags (which means we'd only be leaving off three of them) I just wonder if it's worth leaving the other 3 flags off. I'll have a think about it at any rate.

**Comment by fgsch** [comment]
Done in b96f5152a3d08e6b75fe1b1a8eeffed0c5121cf7.
