### ISSUE TITLE
fastly compute init should use SNI and Override host for origins

### ISSUE THREAD

**Issue by acme** [fastly/cli#241]
Would it be possible for `fastly compute init` when adding an origin over TLS to use the hostname for `SNI hostname` and `Override host` too? All the origins I talk to require SNI and to pass the real host, not the funny-three-words host, so I then have to go into the UI to fix it.

**Comment by fgsch** [comment]
I've run into this problem today while testing a C@E service created with the CLI. 
Adding the backend through the UI did set the `SNI hostname` (and `Certificate hostname`) correctly.

**Comment by fgsch** [comment]
@acme would #352 do the job for your use case?

**Comment by acme** [comment]
Thanks, this now works great for me! 👏
