### ISSUE TITLE
Compute Edge hashsum should be the hash of main.wasm

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#243]
Currently we hash the tarball, which might contain a newly generated `main.wasm` if `compute build` was issued before.
Furthermore, the tarball does not preserve the dates and times of e.g. `Cargo.toml` or `fastly.toml`, resulting on different hashes every time the tarball is created. 

To avoid this situation, and only create new revisions when the binary changes, we want to change the code to only compute and use the hash of `main.wasm`.

CC @phamann

**Comment by StarpTech** [comment]
Hi, I run into the same issue. Due to this fail, pulumi always wants to redeploy my service.
