### ISSUE TITLE
Add support for postprocessors

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#254]
If wizer (https://github.com/bytecodealliance/wizer) is available and enabled via e.g. `--with-wizer` parameter, run the wizer cli with the wasm file before creating a package.

**Comment by Integralist** [comment]
I was just about to comment to say I wasn't keen on the direct support for a specific tool and that a generalised approach would be preferred. So I agree that having a post-processor flag seems a more flexible option.

**Comment by phamann** [comment]
We should discuss this internally with the WebAssembly team, as they may be a valid argument for us always running `wizer` on binaries, however this could/should be moved to the server side compilation step and not pushed to the user.

**Comment by fgsch** [comment]
@phamann if we were talking about `wizer` only perhaps, but there might be other things that people want to do here.
That's why I changed the title from `wizer` to the more generic `postprocessors`.

Also, I don't think we want to run `wizer` unconditionally for various reasons.

**Comment by fgsch** [comment]
I believe this is now enabled by #480. Closing.
