### ISSUE TITLE
Update rustup error to cover package managers

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#269]
If `rustup` was installed via a package manager (e.g. homebrew) and needs to be updated, the provided instructions will not work:

```
error: self-update is disabled for this build of rustup
error: you should probably use your system package manager to update rustup
```

We might want to reword the instructions to cover this case.

Reported from @gaastonsr via #137.

**Comment by Integralist** [comment]
Yup looks like Homebrew has this configured:

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rustup-init.rb#L30

**Comment by fgsch** [comment]
I wonder what our position on this should be, besides this particular case.

For example, if rustup is not installed, we tell people to use `curl https://sh.rustup.rs -sSf | sh`, so it makes sense that we also tell people to use `rustup self update`.

In other words, should we account for package managers in all instructions?

**Comment by Integralist** [comment]
Oh! I just realised we already tell people to use the official channel https://sh.rustup.rs so in this case I'm not sure we have a solid way to solve this problem because we can't identify the error as being related to a package manager without pattern matching the error (which could be different across OS').

**Comment by fgsch** [comment]
Right. I was not suggesting to cover every package manager but rather change the wording to something like this:

```
If you installed rustup using a package manager, refer to its documentation to update it.
```

**Comment by iyerrama29** [comment]
Hi there, I'm facing this issue as well

## Steps followed

- Insatlled rust up using the following command
	- curl https://sh.rustup.rs -sSf | sh
- Installed nightly
	- rustup toolchain add nightly
- Ran fastly compute
	- fastly compute build

I keep receiving the following error

```sh
✓ Initializing...
✓ Verifying package manifest...
✗ Verifying local rust toolchain...

ERROR: error reading cargo metadata: EOF.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

## Cargo.toml file has this
```sh
[package]
name = "compute-starter-kit-rust-default"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.6.0"
```

## rust-toolchain file looks like this
```sh
[toolchain]
channel = "1.49.0"
targets = [ "wasm32-wasi" ]
```

## Fastly version is

```sh
Fastly CLI version 0.30.0 (326882f)
Built with go version go1.16.4 linux/amd64
```

## Rustup version is

```sh
rustup 1.24.2 (755e2b07e 2021-05-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`
```

**Comment by gaastonsr** [comment]
I discovered that the error `ERROR: error reading cargo metadata: EOF.` can pop up when cargo or rustup has an error. Unfortunately, right now the error message is not propagated so the generic error presented is confusing.

My advice would be to run `cargo build` and see if cargo succeeds or shows an error.

**Comment by iyerrama29** [comment]
I debugged this and tried to install the dependencies via `cargo build`

Turns out, it was picking up the Cargo.toml file from the parent directory. Deleting that worked. But is now resulting in a new error:
```sh
error[E0599]: no associated item named `HTTPINVALID` found for struct `FastlyStatus` in the current scope
    --> /home/ramanathan/.cargo/registry/src/github.com-1ecc6299db9ec823/fastly-0.7.1/src/http/request.rs:2198:42
     |
2198 |             fastly_shared::FastlyStatus::HTTPINVALID => SendErrorCause::Invalid,
     |                                          ^^^^^^^^^^^ associated item not found in `FastlyStatus`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `fastly`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

**Comment by fgsch** [comment]
@iyerrama29 Do you mind open a new ticket so we can track it down? Thank you!

**Comment by iyerrama29** [comment]
Sure @fgsch
