### ISSUE TITLE
Don't display the fastly token in the terminal when doing `fastly configure`

### ISSUE THREAD

**Issue by psbanka** [fastly/cli#27]
**Version**

0.5.0

**What happened**

The CLI outputs the value of `$FASTLY_API_TOKEN` to the terminal when running `fastly configure`. This is an unexpected and unnecessary security risk. This would be less of a shock to the user if you displayed it only when issuing the command with a `-v` flag.

**Comment by phamann** [comment]
Thank you for finding and reporting this @psbanka , I have fixed in #30

**Comment by transitorykris** [comment]
Is it possible to show that characters have been entered?
