### ISSUE TITLE
Mention fastly compute publish when init-ialising a package?

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#270]
When `fastly compute init` finishes you see:

```
To compile the package, run:
	fastly compute build

To deploy the package, run:
	fastly compute deploy
```

Do we want to mention `fastly compute publish` as well or instead build and deploy?

**Comment by Integralist** [comment]
If the general consensus is that this is valuable to be added, then I'm happy for a PR to be opened to implement this. 

My only concern is whether this is worth the extra visual noise (as a side note: there are plans to display other information/messing in that area and so things could start getting a little busy). It also feels a little redundant to display all three build/deploy/publish when the latter is just a convenience for "build _and_ deploy". The `publish` subcommand is also easily discoverable and feels more like a power user feature.

**Comment by fgsch** [comment]
To me is the other way around - I'd expect folks to use the `publish` subcommand more than `build` and `deploy` separately.

**Comment by triblondon** [comment]
I agree, and I think I'd like to see this reduced to just advise the user to `publish`.

**Comment by phamann** [comment]
hmmm. In a world with Viceroy and `fastly compute serve` the natural next steps to offer is build and serve, (especially as serve doesn't yet automatically build if it there are changes). So I disagree that this is so clear cut.
