### ISSUE TITLE
Support using local git repositories, or just plain directories, as sources for `fastly compute init`

### ISSUE THREAD

**Issue by tschneidereit** [fastly/cli#271]
**Version**

Fastly CLI version 0.27.2 (7795612)
Built with go version go1.16.3 linux/amd64

**What happened**

It's more about what I'd like to happen ;) I'd like to make it easier for our customers to test pre-release versions of SDKs. To that end, it'd be great if we could provide them with a tarball for a starter kit, and then use `fastly compute init -f [path/to/starter/kit]`.

Currently, we have to instead provide directions for initializing a service from a public starter kit, and then copy over the resulting `fastly.toml` file into a fresh copy of the prerelease starter kit.

**Comment by kailan** [comment]
Are you aware of the `--from` flag, which takes a Git repository?

https://developer.fastly.com/reference/cli/compute/init/#options

I believe this works with plain directories too.

**Comment by tschneidereit** [comment]
ooh, that *does* now work! When I last tried it sometime early in the year it didn't, and I hadn't seen anything about that changing. I should've checked before opening this issue though—apologies for the noise, and thank you for the quick response! <3

**Comment by tschneidereit** [comment]
Reopening because this doesn't work anymore.

**Comment by Integralist** [comment]
Looks like the code is still there https://github.com/fastly/cli/blob/main/pkg/compute/init.go#L368-L450 and it's part of the overall `compute init` flow. @tschneidereit what error are you seeing now?

**Comment by williamoverton** [comment]
Thread from slack: https://fastly.slack.com/archives/C01E7FV8P5H/p1625500582141300

**Comment by kailan** [comment]
I have a use case for Fiddle that would make it really helpful for the CLI to accept a URL to a remote .tar.gz archive as a value for the `--from` flag. Should I spin this off into another issue?

**Comment by Integralist** [comment]
Yes please @kailan. 

I also think this current issue can be closed again? 
As I believe @tschneidereit confirmed internally it works with latest 0.33.0 release (is that correct?)

**Comment by tschneidereit** [comment]
Closing again, because it looks like whatever might've been broken in the meantime is fixed in 0.33.0 :)
