### ISSUE TITLE
docs: Publish to GoDoc

### ISSUE THREAD

**Issue by timoguin** [fastly/cli#29]
Rather than code dive right off the bat, I first searched for this package on the GoDoc site, but it's not published. It would be great if this package could be published to the GoDoc site. I believe this would require some refactoring to use the full GitHub paths for the package names (and imports), which would allow GoDoc to generate it automatically and index it on the GoDoc site.

### References

- https://github.com/golang/go/wiki/PackagePublishing

**Comment by phamann** [comment]
Hi @timoguin, thanks for raising the issue. 

Whilst we'll happily publish the package to GoDoc, It won't be that useful to anyone other than people developing the CLI - and even then pretty limited. We don't intended the cli packages to be used or consumed elsewhere outside of this repository hence why it wasn't originally published. 

It would be good to understand your use-case for wanting the GoDoc? Or where you actually looking for documentation for the commands you can run via the CLI as a user?

**Comment by timoguin** [comment]
Hi, @phamann! Thanks for the quick reply!

My use case was just initial exploration. I've looked at the go-fastly SDK and was curious how it might be consumed by a Golang-based CLI. I found this official one and wanted to dig into how the code base was structured. I'm used to code diving, but felt it might be quicker to consume via GoDoc. I did notice that there is documentation, just not published.

**Comment by peterbourgon** [comment]
Docs are available at https://pkg.go.dev/github.com/fastly/cli
