### ISSUE TITLE
Feature request: take service ID from FASTLY_SERVICE_ID 

### ISSUE THREAD

**Issue by peterbourgon** [fastly/cli#301]
I tend to use the CLI in a "session" where I am working on various properties of a single service. Basically every time I invoke `fastly` I have to pass a service ID as a parameter.

If I happen to be in a directory with a `fastly.toml` manifest file, I can put the service ID in there, where it's used as a default. Otherwise, I have to specify `--service-id` with each command. This immediately becomes very tedious, for what I hope are obvious reasons.

It should be possible to specify a service ID via a `FASTLY_SERVICE_ID` env var. In case the service ID is specified in multiple ways, the priority order would be

1. File (lowest priority)
2. Env var
3. Flag (highest priority)

Let me know if you're down to clown, I can do the PR.

**Comment by Integralist** [comment]
This makes sense to me. Happy for you to contribute a PR 👍🏻
