### ISSUE TITLE
fastly compute publish doesn't respect --service-id

### ISSUE THREAD

**Issue by gaastonsr** [fastly/cli#304]
**Version**

```sh
Fastly CLI version 0.30.0 (326882f)
Built with go version go1.16.4 linux/amd64
```

**What happened**

Hi! I have a Compute@Edge package that I want to deploy to different services (staging, production, etc), so I need to be able to specify the id of the service I want to deploy when running `fastly compute publish`.

I've tried the following without success:

**Attempt 1**

If I remove the `service_id` from `fastly.toml` and then I try to deploy with `fastly compute publish --service-id=SERVICE_ID` I get the error: 

```
There is no Fastly service associated with this package. To connect to an existing service
add the Service ID to the fastly.toml file, otherwise follow the prompts to create a
service now.
```

And then shows me a prompt to create a new service, which I don't want.

**Attempt 2**

If I set a dummy `service_id=dummy_id` in `fastly.toml` and then I overwrite it with `--service-id=SERVICE_ID` when I run `fastly compute publish --service-id=SERVICE_ID` I get the following error: `ERROR: the Fastly API returned 404 Not Found: Record not found (Cannot find service 'dummy_id').`

I consider this to be a bug because when I run `fastly compute publish --help` in the optional flags it lists `--service-id` as a valid option.

**Comment by fgsch** [comment]
I believe this was fixed by https://github.com/fastly/cli/pull/292. 
Could you try main and let us know?

**Comment by gaastonsr** [comment]
I can confirm it's fixed in main. When is a new version released?

**Comment by gaastonsr** [comment]
Btw it works in main but it works in a way that was unexpected to me. I filed a new bug https://github.com/fastly/cli/issues/305.

**Comment by Integralist** [comment]
Hi @gaastonsr I had planned for a new version to be released early this week.

I'll review your follow-up issue today.
