### ISSUE TITLE
fastly compute publish --service-id replaces the service_id value in fastly.toml

### ISSUE THREAD

**Issue by gaastonsr** [fastly/cli#305]
**Version**

```sh
Fastly CLI version v0.30.0-21-g24734d4 (24734d4)
Built with go version go1.16.4 darwin/amd64
```

**What happened**

Hi! I'm using `fastly compute publish --service-id` to deploy the same package to multiple services (staging, production, etc). The problem that I'm facing is that every time I use that command it replaces the `service_id` in my `fastly.toml` file.

In my case this is undesirable because if somebody forgets to use `--service-id` they might deploy to the wrong service. Ideally, `--service-id` simply takes precedence over the service id value in `fastly.toml` without overwriting the file.

**Comment by Integralist** [comment]
Thanks @gaastonsr I implemented that behaviour, but in hindsight I believe that was a mistake and agree that your use case is the more common scenario so I've opened a PR to fix this issue: https://github.com/fastly/cli/pull/307
