### ISSUE TITLE
Add --features flag to fastly compute build command

### ISSUE THREAD

**Issue by gaastonsr** [fastly/cli#322]
**Version**
```
Fastly CLI version 0.31.0 (e2b6042)
Built with go version go1.16.5 linux/amd64
```

**What happened**

Not sure if here's the appropriate place to post this but I was wondering if it was possible to add a `--features` flag to the `fastly compute build` or `fastly compute publish` commands so we could customize the builds that are produced.

My use case is that I have a project that I want to deploy to multiple environments (prod, staging, etc) but I want to build slightly different builds for each one.

**Comment by rubyroobs** [comment]
Following - this would be extremely useful for my use case as well.

**Comment by peterbourgon** [comment]
@gaastonsr What should `--features` do?

**Comment by gaastonsr** [comment]
[The same that it does in cargo](https://doc.rust-lang.org/cargo/reference/features.html). Basically, add conditional compilation, this is integrated in cargo/Rust already, we would just need to pass that flag to cargo when building.

**Comment by peterbourgon** [comment]
And in other languages?

**Comment by gaastonsr** [comment]
Good point. Although it would be a shame that we miss out features that are built-in in a language because not all the languages support it.

**Comment by fgsch** [comment]
Covered with the introduction of #484.

**Comment by Integralist** [comment]
Custom builds are now possible and I'm going to close this ticket in favour of https://github.com/fastly/cli/issues/509
