### ISSUE TITLE
fastly compute publish and deploy should accept a comment

### ISSUE THREAD

**Issue by acme** [fastly/cli#328]
**Version**

Fastly CLI version 0.32.0 (802bf7b)
Built with go version go1.16.5 linux/amd64

**What happened**

I leave a comment on every Fastly service version when working with VCL services to note what has changed in that version. It'd be great if we could use the same mechanism with C@E services.

Fastly service versions can have a comment:

* UI example: https://docs.fastly.com/en/guides/working-with-services#adding-comments-to-service-versions
* API example: https://developer.fastly.com/reference/api/services/version/
* `fastly service-version update` already supports `--comment` option: https://developer.fastly.com/reference/cli/service-version/update/

Perhaps`fastly compute publish` and `fastly compute deploy` could support a `--comment` option?

I don't think it makes sense to autogenerate a comment?

**Comment by bbutkovic** [comment]
Hey, I tackled this in #343, hope it helps.
