### ISSUE TITLE
Rewriting fastly.toml strips out some properties

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#393]
**Version**

Fastly CLI version 0.37.1 (e100937)

**What happened**

When running `fastly compute serve` I noticed dictionary lookups were causing panics. 
Upon further inspection, I found that the CLI was stripping out some properties (e.g. local_server.dictionaries) when rewriting the fastly.toml and the original input did not have `manifest_version`.

fwiw, the same file works without changes in Viceroy.

**Comment by Integralist** [comment]
Hi @fgsch 

Can you include an example `fastly.toml` file so I can use that as a reduced test case.

Thanks!

**Comment by fgsch** [comment]
The same happens if I run `fastly init` with an existing fastly.toml (and valid `manifest_version`). Some properties are removed but not others.

**Comment by fgsch** [comment]
Sample input:

```
[local_server.backends]
  [local_server.backends.origin]
  url = "http://localhost:7879"
[local_server.dictionaries]
  strings = { file = "strings.json", format = "json" }
```

**Comment by Integralist** [comment]
Looks like the CLI just needs to know about the Dictionary support (as per https://developer.fastly.com/reference/fastly-toml/).

> **NOTE**: Looks like the existing `Backend` support needs to be updated to reflect a new `override_host` property.
