### ISSUE TITLE
`fastly compute serve` should not treat stderr output as an error

### ISSUE THREAD

**Issue by peterbourgon** [fastly/cli#400]
```
ugh ~ fastly version
Fastly CLI version 0.37.1 (e100937)
Built with go version go1.17 linux/amd64
```

```
ugh ~ fastly compute serve ...
...
✓ Initializing...
✓ Checking latest Viceroy release...
✓ Checking installed Viceroy version...
✓ Running local server...
...
ERROR: error during execution process:
<stuff I printed to stderr in my program>
```

Printing to stderr does not mean that there was actually an error, the only thing that indicates that is a nonzero exit code.

**Comment by Integralist** [comment]
From what I can see...

https://github.com/fastly/cli/blob/1281c721da619e40ea1e7681a989c5e6fa671971/pkg/exec/exec.go#L83-L95

...[`exec.Cmd.Run()`](https://pkg.go.dev/os/exec@go1.17#Cmd.Run) determined there was an error and so we're just grabbing the stderr and printing it as some extra context.

**Comment by peterbourgon** [comment]
Bizarre! This must mean that `viceroy` handles ctrl-C (SIGINT, SIGTERM) by returning nonzero, as that's what I did to elicit this behavior...

**Comment by peterbourgon** [comment]
Filed fastly/Viceroy#73 so I guess this can be closed.
