### ISSUE TITLE
fastly compute publish does not work for language other

### ISSUE THREAD

**Issue by fgsch** [fastly/cli#408]
**Version**

Fastly CLI version 0.38.0 (16317d6)
Built with go version go1.17 linux/amd64

**What happened**

Running "fastly compute publish" fails if the language is other:

```
✓ Initializing...
✗ Verifying package manifest...

ERROR: unsupported language other.
```

Even if the package is already built. For language "other", the only way to deploy a service is with "fastly compute deploy".
This might be an acceptable limitation as it looks like "fastly compute build" always builds the package, and so will do "fastly compute publish", and packaging is done via "fastly compute pack".

**Comment by Integralist** [comment]
With the latest code merged into `main` the `compute publish` command now works because we have fixed the CLI so that `compute build` works with custom builds.
