### ISSUE TITLE
ERROR: error downloading latest Viceroy release: no asset found for your OS (linux) and architecture (386).

### ISSUE THREAD

**Issue by epolish** [fastly/cli#419]
**Version**

Fastly CLI version 0.39.1 (12e4517)
Built with go version go1.17.1 linux/amd64

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**What happened**

ERROR: error downloading latest Viceroy release: no asset found for your OS (linux) and architecture (386).

Steps to reproduce:
fastly compute init
fastly compute build
fastly compute serve

**Comment by Integralist** [comment]
Hi @epolish thanks for raising this issue. It looks like there are only macOS and Linux amd64 builds at the moment: https://github.com/fastly/Viceroy/releases/tag/v0.2.2

This isn't a problem with the CLI itself but with Viceroy not publishing a version of its binary for your OS/Arch combination. So I'll close this issue and open an issue on Viceroy for you (and I'll tag you in it so you have visibility).
