### ISSUE TITLE
`--customer-id` flag is missing description in `fastly user list`

### ISSUE THREAD

**Issue by kailan** [fastly/cli#424]
https://github.com/fastly/cli/blob/main/pkg/commands/user/list.go#L21

```
{
  name: 'list',
  description: 'List all users from a specified customer id',
  subcommands: [],
  options: [
    {
      name: '--customer-id',
      description: 'c',
      args: [
        {
          name: 'customer-id',
        },
      ],
    },
  ],
}
```

<br/>
<br/>

`fastly auth-token` uses the following description for the same flag:
> Alphanumeric string identifying the customer

**Comment by Integralist** [comment]
Yup looks, like the API reference uses the same definition:
https://developer.fastly.com/reference/api/account/customer/#list-users
