### ISSUE TITLE
Fastly CLI `0.39.3` Breaks the `--path` flag

### ISSUE THREAD

**Issue by torch2424** [fastly/cli#432]
# My Use Case

I'm currently writing a Github Action, and testing with [act](https://github.com/nektos/act), and I noticed that using the latest version of the CLI, it breaks, when my local version was working. I was debugging between the two versions, and I have determined that the `--path` breaks between `0.39.2` and `0.39.3`

## Fastly CLI 0.39.2

```
| > compute-sdk-test-waiting@0.2.0 pack /home/torch2424/Source/compute-sdk-ci-github-action/compute-sdk-test-waiting
| > fastly compute pack --path bin/main.wasm
| 
✓ Initializing...
✓ Copying wasm binary...
✓ Copying manifest...
✓ Creating .tar.gz file...
| Running the C@E test for GET / ...
|  
| Deploying the waiting app....
| /home/torch2424/Source/compute-sdk-ci-github-action
| 
✓ Initializing...
✓ Uploading package...
✓ Activating version...
| 
| Manage this service at:
| 	https://manage.fastly.com/configure/services/2OFt4iXPSaKWADeT4jh4hN
| 
| View this service at:
| 	https://initially-probable-condor.edgecompute.app
| 
| 
| SUCCESS: Deployed package (service 2OFt4iXPSaKWADeT4jh4hN, version 11)
| Deployed!!
| Deploying the module....
[Compute SDK Test Backend/backendtest]   ✅  Success - Compute SDK Test Backend
```

## Fastly CLI 0.39.3

```
| > compute-sdk-test-waiting@0.2.0 pack /home/torch2424/Source/compute-sdk-ci-github-action/compute-sdk-test-waiting
| > fastly compute pack --path bin/main.wasm
| 
✓ Initializing...
✓ Copying wasm binary...
✓ Copying manifest...
✓ Creating .tar.gz file...
| Running the C@E test for GET / ...
|  
| Deploying the waiting app....
| /home/torch2424/Source/compute-sdk-ci-github-action
| 
| ERROR: error reading package manifest.
| 
| Run `fastly compute init` to ensure a correctly configured manifest. See more at https://developer.fastly.com/reference/fastly-toml/
[Compute SDK Test Backend/backendtest]   ❗  ::error::Command failed: pwd && fastly compute deploy --token *** --service-id 2OFt4iXPSaKWADeT4jh4hN --path ./compute-sdk-test-waiting/pkg/compute-sdk-test-waiting.tar.gz
[Compute SDK Test Backend/backendtest]   ❌  Failure - Compute SDK Test Backend
Error: exit with `FAILURE`: 1
```

And! If you don't use `--path` in Fastly CLI `0.39.3`, we can confirm that it is not a package manifest error by navigating to the project in question:

```
torch2424 at torch2424-XPS-13-7390 in ~/Source/compute-sdk-ci-github-action/compute-sdk-test-waiting on torch2424/ci-test-on-compute*
$ fastly compute deploy --service-id 2OFt4iXPSaKWADeT4jh4hN
✓ Initializing...
✓ Uploading package...
✓ Activating version...

Manage this service at:
	https://manage.fastly.com/configure/services/2OFt4iXPSaKWADeT4jh4hN

View this service at:
	https://initially-probable-condor.edgecompute.app


SUCCESS: Deployed package (service 2OFt4iXPSaKWADeT4jh4hN, version 12)
torch2424 at torch2424-XPS-13-7390 in ~/Source/compute-sdk-ci-github-action/compute-sdk-test-waiting on torch2424/ci-test-on-compute*
$ fastly version
Fastly CLI version 0.39.3 (d6e5941)
Built with go version go1.17.1 linux/amd64
```

**Comment by Integralist** [comment]
Thanks @torch2424 so here are the steps I took, following on from your feedback...

- `fastly compute init` (pick JavaScript language and then use the [default starter kit](https://github.com/fastly/compute-starter-kit-javascript-default))
- `npm run build` (gives me a warning about 'mode' option not set so defaults to 'production')
- `fastly compute pack --path ./bin/main.wasm`
- `fastly compute deploy --service-id [REDACTED] --path pkg/testing-cli.tar.gz`

This flow works fine (i.e. deploys successfully). 

So this leads me to think that your `fastly.toml` manifest file might have something misconfigured within it.

**Comment by torch2424** [comment]
@Integralist Ah! So this is slightly different from what I am doing! 😄 

You did: `fastly compute deploy --service-id [REDACTED] --path pkg/testing-cli.tar.gz`

However, I did: `fastly compute deploy --service-id [REDACTED] --path ./test/pkg/test.tar.gz`

---

So! When I deploy, I am one directory up from the actual project. My project actually has a few C@E apps in it, and the root of the project is where I'm deploying C@E apps, inside of child directories (I hope that makes sense 😅 ).

So either: The CLI doesn't look for the fastly.toml inside of the tar.gz , or I misunderstood the CLI and I need to deploy from the child directory. (However, it worked in 0.39.2).

Let me know what the right answer is here. Thanks! 😄 🙏🏾
