### ISSUE TITLE
Display build output for javascript apps

### ISSUE THREAD

**Issue by williamoverton** [fastly/cli#474]
**Version**

Fastly CLI version 1.1.1 (f40c221)
Built with go version go1.17.3 linux/amd64

**What happened**

When running `fastly compute build` the output if build errors is not included:

```
# fastly compute build
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✗ Building package using javascript toolchain...

ERROR: error during execution process:
exit status 1.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

This makes it hard to debug errors. Errors can be seen by running `npm run build` manually.

**Comment by Integralist** [comment]
@williamoverton I believe this is now resolved? If so could you close this issue. Thanks!
