### ISSUE TITLE
support FASTLY_CUSTOMER_ID env variable

### ISSUE THREAD

**Issue by cori** [fastly/cli#477]
**Version**

Fastly CLI version 1.1.1 (f40c221)
Built with go version go1.17.3 linux/amd64

**What happened**

I have `FASTLY_CUSTOMER_ID` set as an environment variable as well as `FASTLY_API_TOKEN`, and a script that I use to switch between customer accounts / environments. 

1. execute `fastly user list`
2. expect to get a list of users in the environment / account I'm currently using
3. actually get a prompt to provide `--customer-id`
4. execute `fastly user list --customer-id=$FASTLY_CUSTOMER_ID`
5. receive a list of users for the specified account

**Comment by Integralist** [comment]
Hi @cori 

Thanks for opening this issue. I see you've marked it as a 'bug' but unless I'm mistaken the CLI has never supported the `FASTLY_CUSTOMER_ID` environment variable so I believe this should be marked as a 'feature request'.

**Comment by cori** [comment]
I guess "bug" is the default - I did not select a label at all, and cant seem to update it.

**Comment by cori** [comment]
There's no gear icon, for example"

![image](https://user-images.githubusercontent.com/46317/143031108-38c49357-c11e-4878-854e-dc70d4fae890.png)

**Comment by Integralist** [comment]
Ah! OK no problem, let me update the label 👍🏻 🙂
