### ISSUE TITLE
Allow use of --service-name as an swap-in replacement for -s / --service-id in calls that require is

### ISSUE THREAD

**Issue by cori** [fastly/cli#481]
**Version**

Fastly CLI version 1.1.1 (f40c221)
Built with go version go1.17.3 linux/amd64

**What happened**

when doing cli operations on elements that require a service specification, it would be great to be able to use the service's name instead of its id, perhaps via `--service-name`. 

Unless I'm misunderstanding something, service names are equally unique in the contexts that you need to specify a service id (activities like `fastly backend *` or `fastly domain *`), and remembering the name of the service I'm working on would be much much easier than having to look it up via `fastly service list`, but unfortunately it doesn't make as much sense to set as an env variable as facts like `FASTLY_API_TOKEN` or `FASTLY_CUSTOMER_ID`.

**Comment by cori** [comment]
This is definitely a Feature Request. It seems like the missing bit there might be the fact that there's a template for bug reports that sets the `bug` label, but not one for feature requests that sets the `feature request` label.

**Comment by Integralist** [comment]
Thanks @cori FYI I've just added a new template to resolve this 👍🏻  https://github.com/fastly/cli/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by cori** [comment]
Perfect; thanks!
