### ISSUE TITLE
--watch stops watching on build error

### ISSUE THREAD

**Issue by williamoverton** [fastly/cli#485]
**Version**

Fastly CLI version 1.3.0 (0a365cb)
Built with go version go1.17.3 linux/amd64

**What happened**

When running `fastly compute serve --watch` everything works fine until you have a build failure (e.g. syntax error). This causes the fastly cli to exit requiring you to run the serve command again.

**Comment by mdenomy** [comment]
I think this can be closed. Seems to have been fixed in https://github.com/fastly/cli/pull/551

**Comment by GeeWee** [comment]
Seems to work
