### ISSUE TITLE
[FEATURE REQUEST] Support for adding Conditions 

### ISSUE THREAD

**Issue by eabquina** [fastly/cli#497]
**Is your feature request related to a problem? Please describe.**
We've been using Fastly CLI for orchestration, and we realized that adding conditions is not available in the CLI
https://developer.fastly.com/reference/api/vcl-services/condition/

**Describe the solution you'd like**
Provide a new command to add `condition` 
https://developer.fastly.com/reference/api/vcl-services/condition/

**Comment by Integralist** [comment]
Hi @eabquina thanks for opening this issue.

I'm unable to give an exact timeline for if/when this feature would be added to the CLI, but I would like to mention that conditional logic can be defined directly within your VCL code.

VCL code can be managed by the CLI using:

- `fastly vcl custom ...`
- `fastly vcl snippet ...`

Is there any reason that you're not able to utilise conditional logic in this way, and is there any additional context you can provide as to what your workflow/orchestration looks like? As it may help us to assign a priority level for implementing the conditional API feature.

Many thanks!

**Comment by Integralist** [comment]
Going to close this issue for now as the CLI is able to support conditions indirectly via custom VCL code or VCL snippets.
