### ISSUE TITLE
Error : context deadline exceeded

### ISSUE THREAD

**Issue by byteshiva** [fastly/cli#498]
**Version**
```fastly version 
Fastly CLI version 1.3.0 (0a365cb)
Built with go version go1.17.3 linux/amd64
```

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.

Please paste the output of `fastly version` here.

**What happened**

When I do `fastly version` and it throws "context deadline exceeded"

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.

Please describe the command you ran, what you expected to happen, and what happened instead.

**Comment by fgsch** [comment]
Sounds like a dup of #289.

**Comment by Integralist** [comment]
Agreed @fgsch. I'll close this as a duplication of #289
