### ISSUE TITLE
ERROR: error during compilation process: exit status 101.

### ISSUE THREAD

**Issue by DonFuego** [fastly/cli#52]
**Version**

Fastly CLI version 0.7.1 (34ea541)

**What happened**

Running through the getting started guide during the `fastly compute build` produces this error.

**Comment by thommahoney** [comment]
CLI v0.7.0 bumped up the required version of Rust to 1.43.0, which could be related. Can you run command with a `-v` flag and report back?

```shell
fastly compute build -v
```

**Comment by phamann** [comment]
Hi @DonFuego thanks for the report. This error is normally caused by a Rust compilation error (i.e. an issue with your program), by default we suppress the output from `cargo build` during compute build, however if you pass the verbose flag to `fastly compute build` i.e. `fastly compute build -v` it will stream the output from the Rust compiler to stdout and you'll be able to see the actual error.

I agree that the error message here isn't that helpful so i'll make sure to add a ticket to make it more descriptive.

**Comment by DonFuego** [comment]
Sure, here you go for `fastly compute build -v`

`➜ fastly compute build -v
Fastly API token provided via FASTLY_API_TOKEN
Fastly API endpoint: https://api.fastly.com
Verifying package manifest...
Verifying local rust toolchain...
Checking if rustup is installed...
Found rustup at /Users/tmatthews/.cargo/bin/rustup
Checking if Rust 1.43.0 is installed...
Checking if wasm32-wasi target is installed...
Found wasm32-wasi target
Found Cargo.toml at /Users/tmatthews/Dev/projects/rust/fastly-wasm/Cargo.toml
Building package using rust toolchain...
    Updating crates.io index
error: failed to get `fastly` as a dependency of package `fastly-template-rust-default v0.1.0 (/Users/tmatthews/Dev/projects/rust/fastly-wasm)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available

ERROR: error during compilation process: exit status 101.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md`

**Comment by phamann** [comment]
Right, so this appears to be an issue with your `cargo` or `rustup` configuration and not the `fastly` binary. It is suggesting your local ssh-agent isn't correctly wired up. A couple of suggestions to remediate:

Try checking if you have Rust toolchain updates to install via:
`rustup check`

Try fixing your ssh-agent, by running `ssh-add` with no arguments.

Try fetching the `fastly` crate manually and see the output:
`cargo install fastly`

Hope this helps, and let us know what the solution was if find it.

**Comment by DonFuego** [comment]
So `rustup check` did show I had been using `1.40.0` instead of `1.43.0`.  So I ran `rustup update` and it installed newer version.  But that didn't seem to do it.  

I did just run `ssh-add` with no params and that seemed to fix the problem.  It's building fine now.  Thanks for the update and quick response!

**Comment by phamann** [comment]
No worries, glad its working!
