### ISSUE TITLE
Error:API rate limit exceeded 

### ISSUE THREAD

**Issue by byteshiva** [fastly/cli#524]
I'm using viceroy for local testing. Can I create my own GitHub Personal token to fetch viceroy?

or 

Is there any flag I can set to avoid fetching the latest viceroy release from Github via fastly cli?

```
docker run --user $(id -u):$(id -g) -p 7676:7676  -v $PWD:/app -it --rm fastly/cli/assemblyscript:17 compute serve --addr="0.0.0.0:7676"
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Building package using javascript toolchain...
✓ Creating package archive...

SUCCESS: Built package 'ClientInfo' (pkg/ClientInfo.tar.gz)

✗ Checking latest Viceroy release...

ERROR: error fetching latest version: GET https://api.github.com/repos/fastly/viceroy/releases/latest: 403 API rate limit exceeded for  xyz.xyz.xyz.xyz (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 9m59s].
```

```

{"message":"API rate limit exceeded for xyz.xyz.xyz.xyz. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

```

**Comment by byteshiva** [comment]
> Out of interest what version of the CLI are you using? As the CLI (as of a couple of releases ago, [1.4.0](https://github.com/fastly/cli/releases/tag/v1.4.0)) was updated with an intended workaround which was to only check for an updated Viceroy once a day: #488 for reference.

Version : 1.4.0
```
docker run --user $(id -u):$(id -g) -p 7676:7676  -v $PWD:/app -it --rm fastly/cli/assemblyscript:17 version   
Fastly CLI version 1.4.0 (e91af24)
Built with go version go1.17.5 linux/amd64
````

In the above, the docker instance is deleted ` docker --rm`  after every build and serve process, I guess the check is happening inside the docker instance. Once Docker Instance is deleted, any further docker instance creation would check again for Viceroy, And if the build is happening multiple times it will throw API exceeded error. 

Maybe a flag from fastly CLI would be useful. Can I pass or set the flag inside `fastly.toml` file to avoid frequent calls to viceroy?

```
	LastChecked   string `toml:"last_checked"`
	LatestVersion string `toml:"latest_version"`

```

**Comment by byteshiva** [comment]
ps:
I see there is an option to set it to 24hrs!
```
[viceroy]
ttl = "24h"
```

**Comment by Integralist** [comment]
Correct, that value inside the config is how long it waits to check again.

The CLI logic that determines whether to check for an updated viceroy version is:

```go
if viceroy.LastChecked != "" && viceroy.LatestVersion != "" && !check.Stale(viceroy.LastChecked, viceroy.TTL) {
  ...
}
```

So ultimately it's checking the config's viceroy `ttl` value against the `last_checked` value and if the ttl is stale (relative to when we last checked) then we'll go ahead and check for a newer version of the viceroy executable. 

If as you say the values are being reset because of how Docker works or the particular workflow that's being used, then maybe you could manipulate those config values yourself when running the container.

**Comment by byteshiva** [comment]
I'll test it and get back to you, are there any unit tests for this scenario.

Maybe I should loop docker instance creation and test this use case.

ps:-
Due to an power outage/accident at my location, I may not be able to test it no sooner than 3 days from today.

**Comment by byteshiva** [comment]
I'll test it and get back to you, are there any unit tests for this scenario.

Maybe I should loop docker instance creation and test this use case.

ps:-
Due to an power outage/accident at my location, I may not be able to test it no sooner than 3 days from today.

**Comment by Integralist** [comment]
> are there any unit tests for this scenario.

There are not. We have integration tests for all the CLI commands, but as we don't officially support Docker at the moment, there are no tests to validate its usage.

> I may not be able to test it no sooner than 3 days from today

No problem. Thanks for the update.

**Comment by byteshiva** [comment]
Notes and observation:

1. `ttl` and `LastChecked` works fine on a standalone installation
2. By default fastly is not packaging `viceroy`, it gets viceroy on `fastly compute serve` command. In the docker instance, I don't see the `viceroy` installed on the home location.

```
docker run -it --entrypoint /bin/bash fastly/cli/assemblyscript:17 
root@:/home/node# cd .config 
bash: cd: .config: No such file or directory
root@:/home/node# ls -rlt 
total 0
```

After executing the first `fastly compute serve` command I'd see it pulls from the net and installs at `$HOME/.config/fastly/`
```
node@:/app$ find / -name viceroy
/home/node/.config/fastly/viceroy
```

With `--rm` option removes docker instance after executing `fastly compute serve`, so if I run the below command multiple times it will cause `API rate limit exceeded. Since there is no viceroy installed by default, it will exhaust the API limit if one executes the below command multiple times. 
```
docker run  --rm --user $(id -u):$(id -g)  -v $PWD:/app -it  fastly/cli/assemblyscript:17 compute serve --skip-build  -v 
```



```

**Comment by byteshiva** [comment]
I've fixed this issue with docker by persisting data by adding two volumes. One volume points to the javascript project(now it can be assemblyScript or node or anything) and the other points to the home directory where the viceroy gets installed.

```
➜  clientinfo docker run --rm  --user $(id -u):$(id -g)  -v $PWD:/app -v $HOME/tmp/fastly/:/home/node/ -it  fastly/cli/assemblyscript:17 compute serve 
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Building package using javascript toolchain...
✓ Creating package archive...

SUCCESS: Built package 'app' (pkg/app.tar.gz)

✓ Checking latest Viceroy release...
✓ Fetching latest Viceroy release...
✓ Running local server...

Feb 06 08:38:20.754  WARN no backend definitions found in /app/fastly.toml
Feb 06 08:38:20.754  INFO Listening on http://127.0.0.1:7676
^C
INFO: Local server stopped

```

```
➜  clientinfo docker run --rm  --user $(id -u):$(id -g)  -v $PWD:/app -v $HOME/tmp/fastly/:/home/node/ -it  fastly/cli/assemblyscript:17 compute serve 
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Building package using javascript toolchain...
✓ Creating package archive...

SUCCESS: Built package 'app' (pkg/app.tar.gz)

✓ Running local server...

Feb 06 08:39:15.287  WARN no backend definitions found in /app/fastly.toml
Feb 06 08:39:15.287  INFO Listening on http://127.0.0.1:7676
^C
INFO: Local server stopped

```

```
➜  clientinfo docker run --rm  --user $(id -u):$(id -g)  -v $PWD:/app -v $HOME/tmp/fastly/:/home/node/ -it  fastly/cli/assemblyscript:17 compute serve --addr="0.0.0.0:7676"
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Building package using javascript toolchain...
✓ Creating package archive...

SUCCESS: Built package 'app' (pkg/app.tar.gz)

✓ Running local server...

Feb 06 08:40:58.306  WARN no backend definitions found in /app/fastly.toml
Feb 06 08:40:58.306  INFO Listening on http://0.0.0.0:7676

```

**Comment by Integralist** [comment]
Thanks for the update @byteshiva.

Although this is an unfortunate side-effect of Docker's workflow, I am glad you managed to reach a workable solution.

I'm going to go ahead and close this issue, and I'll open a PR that adds some comments to the `Dockerfile`s so that future users of them will have a better understanding of this pitfall.
