### ISSUE TITLE
Compute@Edge project fails to build with tracing-bunyan-formatter crate

### ISSUE THREAD

**Issue by kpeters-cbsi** [fastly/cli#532]
**Version**

Fastly CLI version 1.4.0 (e91af24)
Built with go version go1.17.5 linux/amd64
Viceroy version: viceroy 0.2.8

**What happened**

I ran `fastly compute publish --token <TOKEN>` in my project root. I expected it to build and deploy. It appears to be related to the `tracing-bunyan-formatter` crate.

```
Compiling gethostname v0.2.2
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> /Users/cpete0624/.cargo/registry/src/github.com-1ecc6299db9ec823/gethostname-0.2.2/src/lib.rs:65:18
   |
65 |     use std::os::unix::ffi::OsStringExt;
   |                  ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `libc::_SC_HOST_NAME_MAX`
  --> /Users/cpete0624/.cargo/registry/src/github.com-1ecc6299db9ec823/gethostname-0.2.2/src/lib.rs:64:33
   |
64 |     use libc::{c_char, sysconf, _SC_HOST_NAME_MAX};
   |                                 ^^^^^^^^^^^^^^^^^ no `_SC_HOST_NAME_MAX` in the root

error[E0425]: cannot find function `gethostname` in crate `libc`
  --> /Users/cpete0624/.cargo/registry/src/github.com-1ecc6299db9ec823/gethostname-0.2.2/src/lib.rs:70:37
   |
70 |     let returncode = unsafe { libc::gethostname(buffer.as_mut_ptr() as *mut c_char, buffer.len()) };
   |                                     ^^^^^^^^^^^ not found in `libc`
   |
help: consider importing this function
   |
27 | use crate::gethostname;
   |

   Compiling tracing-log v0.1.2
error[E0599]: no function or associated item named `from_vec` found for struct `OsString` in the current scope
  --> /Users/cpete0624/.cargo/registry/src/github.com-1ecc6299db9ec823/gethostname-0.2.2/src/lib.rs:89:15
   |
89 |     OsString::from_vec(buffer)
   |               ^^^^^^^^ function or associated item not found in `OsString`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
27 | use std::os::wasi::ffi::OsStringExt;
   |

Some errors have detailed explanations: E0425, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `gethostname` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed.

```

**Comment by Integralist** [comment]
Hi @kpeters-cbsi 

It looks like the `tracing-bunyan-formatter` crate makes the assumption that the compiled binary is running in a normal unix/windows environment, and it uses a dependency [gethostname](https://crates.io/crates/gethostname) to get the hostname of the host machine at runtime to include in its log line output.

The dependency `gethostname` doesn’t seem to support the `wasm32-unknown-unknown` compilation target and therefore the logic panics when it attempts to read some unix specific data: https://codeberg.org/flausch/gethostname.rs/src/branch/main/src/lib.rs#L61-L90

The solution would be to fix either dependency to compile properly on wasm32. Either by changing the tracing formatter crate to detect the wasm target and not call `gethostname` or change the `gethostname` crate to return a static value if the target is wasm32.

**Comment by kpeters-cbsi** [comment]
I've filed a bug in `tracing-bunyan-formatter`: https://github.com/LukeMathWalker/tracing-bunyan-formatter/issues/12
