### ISSUE TITLE
[Feature Request] Wasm-strip for fastly compute build?

### ISSUE THREAD

**Issue by yannh** [fastly/cli#534]
Would it make sense to run wasm-strip before packing the wasm into a tar.gz when running fastly compute build? The artifact created for https://github.com/fastly/compute-starter-kit-rust-static-content for example is 11MB, but only 600KB when stripped.

Could this affect runtimes / cold start times? It would certainly reduce the size of the package to upload :)

```
$ pwd
/home/yann/compute-starter-kit-rust-static-content/pkg
$ ls -lh main.wasm 
-rw-rw-r-- 1 yann yann 11M Feb 12 18:13 main.wasm
$ ~/bin/wabt-1.0.24/bin/wasm-strip main.wasm 
$ ls -lh main.wasm 
-rw-rw-r-- 1 yann yann 616K Feb 12 18:13 main.wasm
```

**Comment by Integralist** [comment]
Hi @yannh thanks for opening this issue.

Speaking with my colleagues internally, there is only one 'future' concern (that we know of) and that is you would lose good backtraces on panics. The reason it's seen as a 'future' concern is that we don't currently expose those backtraces but they may be exposed in the future.

One thing that we could do is add a new flag that lets users opt into using wasm-strip, so the user opts into the lack of backtraces.

At this point in time I think it's a bit too early to make a decision on how we should move forward, so I'm going to leave this issue open, and I'll revisit it once we have more information.

Thanks again!

**Comment by fgsch** [comment]
Could this be implemented in a `scripts.post_build` command?

**Comment by Integralist** [comment]
@fgsch yup, that is also an option and definitely a less impactful one to implement (as the CLI public interface isn't being added to).

**Comment by Integralist** [comment]
👋🏻 

Quick update to say this is being implemented in https://github.com/fastly/cli/pull/565
