### ISSUE TITLE
[FEATURE REQUEST] Respect `.gitignore` when using `--watch` flag.

### ISSUE THREAD

**Issue by Integralist** [fastly/cli#536]
**Is your feature request related to a problem? Please describe.**
When running `fastly compute serve --watch` certain files, such as Vim `.swp` files, are reported as being changed which causes the project to be recompiled unnnecessarily.

**Describe the solution you'd like**
The `--watch` flag should respect files defined in the user's `.gitignore` file.

**Describe alternatives you've considered**
An alternative might be to implement a new flag like `--watch-pattern` which would let me define a custom set of files to watch. Another alternative to that might be to reverse the logic so there is an `--ignore` flag to allow users to define custom set of files to ignore.

**Comment by fgsch** [comment]
To add to the above, an ideal solution could be a mix of this approaches.
For example `ripgrep` parses the content of `.gitignore` and also supports `--ignore-file PATH`.

**Comment by Integralist** [comment]
Looks like ripgrep also ignores `.ignore`. 

I wonder, if there are no local `.gitignore`, should we respect a global variation of those files?

Here are some of the ripgrep options...

```
        --iglob <GLOB>...
            Include or exclude files and directories for searching that match the given
            glob. This always overrides any other ignore logic. Multiple glob flags may be
            used. Globbing rules match .gitignore globs. Precede a glob with a ! to exclude
            it. Globs are matched case insensitively.

    -i, --ignore-case
            When this flag is provided, the given patterns will be searched case
            insensitively. The case insensitivity rules used by ripgrep conform to
            Unicode's "simple" case folding rules.

            This flag overrides -s/--case-sensitive and -S/--smart-case.

        --ignore-file <PATH>...
            Specifies a path to one or more .gitignore format rules files. These patterns
            are applied after the patterns found in .gitignore and .ignore are applied
            and are matched relative to the current working directory. Multiple additional
            ignore files can be specified by using the --ignore-file flag several times.
            When specifying multiple ignore files, earlier files have lower precedence
            than later files.

            If you are looking for a way to include or exclude files and directories
            directly on the command line, then used -g instead.
```

I don't think we need the solution to be as flexible as ripgrep (as it provides many more options than just these ☝🏻), so I would think the CLI should, to keep things simple, initially just respect a local repo's `.gitignore` or `.ignore` files.

Offering `--ignore-file` as a way to _extend_ that behaviour feels a bit overkill. It makes sense if the existing ignore files can't be edited by a user but then the user could (yes the UX is terrible but as a workaround) _could_ edit the ignore files they have locally and then use `git update-index --assume-unchanged .gitignore` to get git to ignore those changes.

But once you introduce a feature like `--ignore-file` you then need to start offering alternatives that don't require the overhead of a custom ignore file (e.g. `--iglob` and the like). So that's why I'm hesitant in implementing that. 

So maybe let's start small and work our way up to more robust ignore options.

**Comment by Integralist** [comment]
Should have been closed via https://github.com/fastly/cli/pull/555
