### ISSUE TITLE
Fastly CLI Github Workflow installation error

### ISSUE THREAD

**Issue by Christopher-Loumeau-foxnews** [fastly/cli#573]
**Version**

softprops/setup-fastly-cli@v0.1.1

**What happened**

Running a github wokflow and installing Fastly.

here is the setup:

    - name: Setup Fastly CLI
      uses: softprops/setup-fastly-cli@v0.1.1
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_KEY }}

(I have the fastly token in my actions secrets as FASTLY API KEY)
However, when it runs. I get this issue 
ERROR: error parsing arguments: expected command but got configure.

I think this is because when it installs it runs 
/opt/hostedtoolcache/fastly-cli/3.0.0/x64/fastly configure --token ***

instead of fastly config.

How do i go about this?

**Comment by Integralist** [comment]
Hi @Christopher-Loumeau-foxnews 

Thanks for reaching out.

The action you're using (`softprops/setup-fastly-cli`) is an unofficial GitHub action that is not supported by Fastly. 

I would recommend using https://github.com/fastly/compute-actions instead which is officially supported by Fastly.

As you have noted the community action you're using is calling a `configure` command which is no longer exposed by the Fastly CLI.

> **NOTE**: The command that action is trying to use was replaced (as of version `2.0.0`) with the `fastly profile` set of commands. 

I imagine that community action's code is set to just install the latest CLI version but as it hasn't been updated in a while (over a year from a cursory glance at their repo) it's unlikely the author has accounted for major version bumps (which are designed to indicate breaking changes).

With this in mind I would suggest opening an issue on the authors repo (https://github.com/softprops/setup-fastly-cli) so they can be aware of the issue and resolve it their side.

As this isn't a Fastly CLI bug I'm going to close this issue.

Thanks again for reaching out. I hope this information helps.
