### ISSUE TITLE
"fastly auth-token create --password=" saves to shell history with no warning

### ISSUE THREAD

**Issue by BinaryVixen899** [fastly/cli#585]
**Version**

```
alealetal@Ryke ~> fastly version
Fastly CLI version v3.1.0 (7844f9f)
Built with go version go1.18.3 linux/amd64
```

**What happened**

Command I ran

```
alealetal@Ryke ~> fastly auth-token create --password=badpassword

ERROR: the Fastly API returned 403 Forbidden: You must POST /sudo to access this endpoint.
alealetal@Ryke ~ [1]> history | grep badpassword
fastly auth-token create --password=badpassword
```

**What I Expected to Happen** 

For this not to be saved to history, or for a popup to go "hey! You may have saved this to your shell history!" 

**What Happened Instead** 

Saved to history.

**Comment by Integralist** [comment]
I'm going to close this issue as I believe this is a shell-related issue and not something the CLI can solve, as the password is provided to the CLI via a flag but how that value is handled by the shell (e.g. recorded into the shell's history) is dependant on the shell, not the CLI. 

One solution is to provide a password using an environment variable.

**Comment by AriESQ** [comment]
This bug could be addressed by modifying the documentation.
