### ISSUE TITLE
Fastly profile was removed somehow

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#586]
**Version**

Fastly CLI version v3.1.0 (7844f9f)
Built with go version go1.18.3 linux/amd64
Viceroy version: viceroy 0.2.14

**What happened**

I've been running lots of fastly cli commands over the last couple weeks and they've all been fine until the most recent `fastly compute publish -i` which failed with a 500 from Fastly API.
After that command failed, my fastly cli profile disappeared.

```
❯ fastly profile list

No profiles defined. To create a profile, run:
	fastly profile create <name>
```

I've confirmed that my token has not expired, it expires in September.

**Comment by Integralist** [comment]
We should replace the mutex exclusion for the write operation to the config file with an appropriate OS level file locking primitive offered by one of these package: https://pkg.go.dev/search?q=flock

**Comment by JakeChampion** [comment]
There's also this package which is a cross-platform machine level mutex: https://pkg.go.dev/github.com/juju/mutex#section-readme

**Comment by Integralist** [comment]
PR #590 introduced some extra safeguards around the profile data, which upon further testing from Jake (the reporter of this issue) it seems the 'single instance' scenario is no longer happening, and for the 'multiple instances' scenario a workaround of using the `--token` flag/`FASTLY_API_TOKEN` environment variable was found to be sufficient.
