### ISSUE TITLE
error fetching latest `fastly` crate version

### ISSUE THREAD

**Issue by platy** [fastly/cli#643]
**Version**

```
% fastly version
Fastly CLI version v3.3.0 (96b3aa7)
Built with go version go1.19 linux/amd64
Viceroy version: viceroy 0.2.15
```

**What happened**

I ran `fastly compute serve` to serve my Comput@Edge program locally but it failed to fetch a new version of the fastly crate. I could run it with `--skip-verification` in order to build successfully.

```
% fastly compute serve                    
✓ Initializing...
✓ Verifying package manifest...
✗ Verifying local rust toolchain...

ERROR: error fetching latest `fastly` crate version: Get "https://crates.io/api/v1/crates/fastly/versions": context deadline exceeded (Client.Timeout exceeded while awaiting headers).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
% fastly compute serve --skip-verification
✓ Initializing...
✓ Verifying package manifest...
✓ Building package using rust toolchain...
✓ Creating package archive...

SUCCESS: Built package 'edge-api' (pkg/edge-api.tar.gz)
```

**Comment by Integralist** [comment]
Hi @platy is sounds like a network issue, are you still experiencing problems running `fastly compute build` and downloading the latest fastly crate version metadata?

I wonder if this error is related to https://github.com/fastly/cli/issues/289, which is related to a user's DNS configuration being invalid. If I remember correctly the "pure Go resolver" ends up consulting `/etc/resolv.conf` and that file is where the DNS is typically misconfigured.

**Comment by platy** [comment]
I'm not having this problem anymore, maybe it was a network issue, though I didn't notice any other issues at the time. Would it make sense for a netwroking issue when doing this verification to emit a warning instead of failing?

**Comment by Integralist** [comment]
Thanks for the update @platy I agree that although it's important to validate the user's system has all the right tools and associated versions, if information can't be acquired (for whatever reason), then a warning would be better so the CLI could at least 'attempt' to continue with its logic execution. Then at least if things didn't work, then the user would have a warning indicating why that _might_ be (e.g. "we couldn't access all the info we needed to validate you have the right setup").

I'll create a ticket for digging into the existing validation logic 👍🏻
