### ISSUE TITLE
`fastly compute build` fails with `fastly/js-compute@latest`

### ISSUE THREAD

**Issue by cmac4603** [fastly/cli#644]
**Version**
```
$ fastly version
Fastly CLI version v3.3.0 (96b3aa7)
Built with go version go1.19 linux/amd64
Viceroy version: viceroy 0.2.14
```

**What happened**
Responding to `2022.09.14 - SEC-35031 (ASN) Vulnerability within the Fastly Compute@Edge SDK for JavaScript`, updated with `npm install '@fastly/js-compute@latest'` to `0.5.2`.

```
$ fastly compute build
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✗ Building package using javascript toolchain...

ERROR: error during execution process:

error: Found argument '--skip-pkg' which wasn't expected, or isn't valid in this context

USAGE:
    js-compute-runtime [FLAGS] [OPTIONS] [ARGS]

For more information try --help.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

The build works when downgrading `'@fastly/js-compute` javascript dependency.

**Comment by Integralist** [comment]
Hi @cmac4603 

The `--skip-pkg` was removed from the `@fastly/js-compute` dependency in `0.3.0`:
https://github.com/fastly/js-compute-runtime/blob/main/sdk/js-compute/CHANGELOG.md#030-2022-06-29  

If you remove the `--skip-pkg` flag from your `package.json` then upgrading should work.

**Comment by Integralist** [comment]
I'm going to close this issue for now, but feel free to continue the conversation/re-open if you are still having issues.
