### ISSUE TITLE
Cannot purge single URL through CLI or web interface

### ISSUE THREAD

**Issue by feliskio** [fastly/cli#645]
**Version**

Fastly CLI version v3.3.0 (96b3aa7)
Built with go version go1.19 linux/amd64
Viceroy version: viceroy 0.2.15

**What happened**

Please describe the command you ran, what you expected to happen, and what happened instead.

Running `fastly purge --service-id=*** --url=***` to purge an individual url returns a 405 Method Not Allowed response.
Same applies when sending a POST request for the same action through manage.fastly.com. I'd assume that this is an issue with the underlying API rather than the CLI itself.

**Comment by Integralist** [comment]
Hi @feliskio 

**Just to clarify:** 
The value for `--url` should be the target hostname itself.

I just quickly setup a new Fastly VCL service with httpbin.org as a backend and I didn't setup any DNS, I'm just using the 'test URL' that Fastly provides (http://integralist-purge-testing.com.global.prod.fastly.net/).

**So, examples of valid values to pass to `--url` would be:**

- A fully qualified domain (FQD): `http://integralist-purge-testing.com.global.prod.fastly.net/`
- A hostname: `integralist-purge-testing.com.global.prod.fastly.net`

**See also our API reference:**
https://developer.fastly.com/reference/api/purging/#purge-single-url

**Below is a screenshot demonstrating my use of the Fastly CLI to purge this endpoint:**

<img width="1186" alt="Screenshot 2022-09-21 at 11 06 30" src="https://user-images.githubusercontent.com/180050/191477194-41cfab74-d577-42a9-8fa5-4d74d1b54cae.png">

> **NOTE**: You'll notice in the last call that I purposefully provide an invalid value.

I was not able to replicate the `405 Method Not Allowed` response.

**Comment by feliskio** [comment]
I believe that I am doing everything just like you are. Are Service IDs save to share publicly?

**Comment by Integralist** [comment]
Hi @feliskio yes Service IDs are fine to share.

**Comment by feliskio** [comment]
This is the error message I am seeing:

<img width="750" alt="grafik" src="https://user-images.githubusercontent.com/33993147/191564291-db1d26ee-873c-4de5-b04a-f52e69a77106.png">

**Comment by feliskio** [comment]
I think I found the deciding piece of the puzzle @Integralist.
My service intentionally restricts HTTP methods to GET and HEAD. And for whatever reason my custom VCL snippets are also applied to the respective _api.fastly.com_ endpoint. I can only assume that this is unintentional.

As a temporary workaround a passing cache rule applied to requests to _api.fastly.com_ might do the trick.

**Comment by Integralist** [comment]
Hi @feliskio 

Thanks for your patience. 

It would be best to reach out to support@fastly.com to assist as they'll be able to inspect your service and review your configuration. I will close this issue now as I don't believe this is a CLI bug.
