### ISSUE TITLE
[FEATURE REQUEST] fastly compute watch does not watch dependant packages

### ISSUE THREAD

**Issue by GeeWee** [fastly/cli#646]
**Feature request**
We have a Rust-based Compute@Edge workspace that has a structure that looks something like
```
/dir
  ./wasm-api
  ./other-crate
```

Where wasm-api is the fastly package and it depends on other-crate in the same directory.

When I `cd` into `wasm-api` and run `fastly compute serve --watch` it will accurately reload when I change files inside 
`wasm-api` (Yay #551 ), but it does not seem to reload when changing files in `other-crate`

**Describe the solution you'd like**
I would like to have all files in the root directory be watched. Optimally only things that are directly in the dependency graph, but I'll take "watch all the files" as a "good-enough" solution.

I currently have a script I run to get this behaviour (which doesn't analyze the dependency graph, but just rebuilds on any file changes)
```bash
find . -name "*.rs" -not -path "*./target*" | entr -r -s '(cd ./wasm-api && fastly compute serve)'
```

**Comment by Integralist** [comment]
Hi @GeeWee thanks for opening this issue.

I believe the following PR (merged yesterday, but not released yet) will fix the issue you're describing...

https://github.com/fastly/cli/pull/642

Let me know if not, and we can discuss further.

Thanks.

**Comment by GeeWee** [comment]
Ah, I did find that PR, but hadn't realized it hadn't yet been merged in. Will test with a new release when one is available.

**Comment by Integralist** [comment]
Thanks @GeeWee hopefully early next week I'll have a `v4.0.0` CLI release out, which will include that PR.

For now I'm going to close this issue, but feel free to continue the conversation/re-open if the next release doesn't solve your issue.

**Comment by GeeWee** [comment]
Commenting here as this isn't actually fixed. The exact same configuration as listed in the original issues still fails to watch the dependant packages on v4.4.1

**Comment by Integralist** [comment]
Thanks for the update @GeeWee 

I've re-opened this issue and have it on our board to investigate.

**Comment by GeeWee** [comment]
Yes, essentially a rust workspace looks like a tiny monorepo with different crates, so you'd have.

```
/workspace-root
  /crate 1 (fastly compute init'd)
  /crate 2 (dependant package)
```

That's essentially the structure most/all larger rust projects take. It's not possible to use `fastly compute init` in the workspace root (*i think* as you'll need a crate with an actual `main` method.

A specifiable watch directory seems like a pretty good solution though!

**Comment by Integralist** [comment]
@GeeWee Great. I'll be sure to start on this next week 👍🏻

**Comment by Integralist** [comment]
@GeeWee just a 'heads up' for this PR https://github.com/fastly/cli/pull/758 which is waiting a code review from my colleague.
