### ISSUE TITLE
Fastly compute build produces "no bin target named `fastly-compute-project`."

### ISSUE THREAD

**Issue by kpeters-cbsi** [fastly/cli#655]
**Version**
```
Fastly CLI version v4.0.0 (650c4e3)
Built with go version go1.18.6 linux/amd64
Viceroy version: viceroy 0.2.15
```

**What happened**

Just updated my Fastly CLI from 3.3.0 to 4.0 and did `fastly compute build` from my Compute@Edge project directory:

```
fastly compute build     
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local rust toolchain...
✗ Running [scripts.build]...

ERROR: error during execution process:

error: no bin target named `fastly-compute-project`.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

I expected it to build my project.

**Comment by kpeters-cbsi** [comment]
Running `cargo clean` in my project directory and then `fastly compute build` didn't help. However, I was able to build a new project in a temp directory.

**Comment by Integralist** [comment]
Hi @kpeters-cbsi 

Thanks for reporting this issue. 

I believe the solution for you would be to modify the package name in the `Cargo.toml` to be `fastly-compute-project`.

**Comment by Integralist** [comment]
This is because the v4 of the CLI has a 'default' build script it uses now (which it will dynamically add to your `fastly.toml` manifest file) and it's hardcoded to `--bin fastly-compute-project` (which coincides with an update to the Rust starter kits to use that as the new package name).

**Comment by Integralist** [comment]
So if you would prefer to leave the Cargo.toml package name as whatever it's set to, you can instead update the build script in `fastly.toml` to reference the correct `--bin` value.

Clearly I missed a step in my rollout process. Apologies for this confusion.

**Comment by kpeters-cbsi** [comment]
That corrected 

> Hi @kpeters-cbsi
> 
> Thanks for reporting this issue.
> 
> I believe the solution for you would be to modify the package name in the `Cargo.toml` to be `fastly-compute-project`.

That fixed it, thanks. Might be worth noting somewhere in the docs.

**Comment by Integralist** [comment]
Thanks again @kpeters-cbsi I'll either try to implement a patch release to work around the issue (if I can) or as you say document this in an appropriate place (likely itself a patch release with a more specific error message).
