### ISSUE TITLE
[FEATURE REQUEST] Rename dictionaries to config-stores (and keep the old name around for backwards compat)

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#700]
**Is your feature request related to a problem? Please describe.**
Confusing terminology when wanting to use Config Stores features via `fastly.toml`

The language SDKs are deprecating their Dictionary implementations in favour of Config Store however when using Viceroy for local development, the way to configure a local Config Store is to create a `local_server.dictionaries` entry in the `fastly.toml` file. The same is true for the `[setup]` section in `fastly.toml` which the CLI makes use of. -- [developer.fastly.com/reference/compute/fastly-toml/#dictionaries](https://developer.fastly.com/reference/compute/fastly-toml/#dictionaries) 

**Describe the solution you'd like**
It would be nice if those field could also work under the name `config-stores`, keeping support for `dictionaries` for all the existing `fastly.toml` manifests out in the world

**Describe alternatives you've considered**
I've not considered alternatives.

I would like to note that right now I think the CLI is being very strict on what fields can be in `fastly.toml`, if the CLI was relaxed and allowed fields in `fastly.toml` that it didn't understand then the work in Viceroy to support `config-stores` in `fastly.toml` could be done before the same work is done in the Fastly CLI.

**Additional context**
I've opened a sibling issue in Viceroy https://github.com/fastly/Viceroy/issues/198

**Comment by triblondon** [comment]
Dictionaries are not deprecated and not going away.

**Comment by triblondon** [comment]
Sorry, I missed that this is related to viceroy and the definition of dictionaries in fastly.toml, not the CRUD operations on dictionaries like `fastly dictionary create` (which are still needed for VCL services and not going away).  Sorry!

**Comment by JakeChampion** [comment]
This was added a while back 👍  (https://developer.fastly.com/reference/compute/fastly-toml/#config-stores)
