### ISSUE TITLE
Fastly 3.1.1 for Windows fails with `Get "": unsupported protocol scheme ""`

### ISSUE THREAD

**Issue by BinaryVixen899** [fastly/cli#737]
**Version**

Fastly 3.1.1

**What happened**

Running `fastly update` fails with `Get "": unsupported protocol scheme ""` 

This was originally reported by a customer on their install but I verified it on a clean install of my own. Not sure which versions it affects besides this one.

**Comment by Integralist** [comment]
👋🏻 The 3.1.1 release was released a while ago, and so I would suggest the customer use the latest v4.x release instead.

Will close this for now, but feel free to re-open or continue the conversation if there's more to discuss here.
