### ISSUE TITLE
Fastly API returns 404 Not Found, when creating profile

### ISSUE THREAD

**Issue by wbrijesh** [fastly/cli#745]
**Version**

v4.5.0 (c56025c)

**What happened**

I ran "fastly profile create fastly-cli-profile --token=xxxxxxxx"

and got 
ERROR: the Fastly API returned 404 Not Found: Record not found (Cannot find user 'xxxxxxxx').
in response

**Comment by Integralist** [comment]
Hi @wbrijesh 

Unfortunately I was unable to replicate your issue using the latest version of the CLI (`4.6.0`)...

<img width="580" alt="Screenshot 2023-01-05 at 17 38 26" src="https://user-images.githubusercontent.com/180050/210844874-e06328b3-c013-40aa-8569-0cc1805370cd.png">

If you could upgrade using `fastly update` and the try again please.

Thanks.

**Comment by Integralist** [comment]
Going to close this issue for now. Please continue the conversation in the thread if there are still issues.
