### ISSUE TITLE
Error downloading latest release: no asset found for your OS (windows) and architecture (amd64).

### ISSUE THREAD

**Issue by CGeorges** [fastly/cli#755]
**4.30**

Current version: 4.3.0
Latest version: 4.6.1

Initializing...
Updating versioning information...
Checking CLI binary update...
Fetching latest release...

ERROR: error downloading latest release: no asset found for your OS (windows) and architecture (amd64).

**What happened**

fastly.exe update

**Comment by Integralist** [comment]
👋🏻 Hi @CGeorges 

Thanks for raising this issue.

I see what's happened here and I you're going to need to manually download the latest release this time I'm afraid (you can get it from https://github.com/fastly/cli/releases/tag/v4.6.1 and specifically [this asset](https://github.com/fastly/cli/releases/download/v4.6.1/fastly_v4.6.1_windows-amd64.tar.gz)).

Your version of the CLI would have been programmed to look for a `.zip` extension (e.g. `fastly_v4.6.1_windows-amd64.zip`) but we no longer generate zip archives but `.tar.gz` (this was to make the released assets consistent across platforms).
