### ISSUE TITLE
`fastly objectstore create` always returns a 500 response

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#760]
**Version**

Fastly CLI version v4.6.2 (53499a6)
Built with go version go1.18.9 linux/amd64
Viceroy version: viceroy 0.3.2

**What happened**

I am trying to create a new Object Store but the command always errors.

The command I run is:
```shell
fastly objectstore create --name="mystore" --verbose
```

And the output is:
```
Fastly API token provided via config file (profile: user)
Fastly API endpoint: https://api.fastly.com

ERROR: the Fastly API returned 500 Internal Server Error: Internal server error (internal server error).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

**Comment by Integralist** [comment]
This doesn't look to be a CLI issue as (from an internal discussion with Jake) it appears that I'm able to create a new object store like so:

```bash
fastly objectstore create --name mystore_via_cli
```

**Comment by JakeChampion** [comment]
Yes, the issue was the CID had reached the limit for how many attachments it could have. I've spoken to the team and they are going to improve the error message in this scenario to say something more than `internal server error`
