### ISSUE TITLE
New version information should be output to stderr

### ISSUE THREAD

**Issue by joeshaw** [fastly/cli#777]
**Version**

Fastly CLI version v4.6.2 (53499a6)
Built with go version go1.18.9 linux/amd64
Viceroy version: viceroy 0.3.2

A new version of the Fastly CLI is available.
Current version: 4.6.2
Latest version: 5.0.0
Run `fastly update` to get the latest version.

**What happened**

A common case is to pipe the output of the CLI into another program.  I most often do this with API keys.  Something like:

    curl -HFastly-Key:$(fastly profile -o personal token) https://api.fastly.com/...etc...

When there is a new version of the CLI (as I display above), that is output to stdout.  This means that instead of sending just the API token as the `Fastly-Key` header in my example it sends the API token plus the update message.

I know I can suppress this with `--quiet` but IMO the "new version" message should be printed to stderr rather than stdout to avoid interfering with piping the output into other commands.

**Comment by Integralist** [comment]
Hi @joeshaw 👋🏻 

Although I appreciate sending 'update info' to stderr would help with scriptability, the use of stderr is traditionally for 'errors' and 'warnings', of which that information doesn't quite fit.

I had another read through https://clig.dev/ and also Googled for best practices in this regard and I've not found any suggestion that stderr should be overloaded to handle anything outside of errors or warnings. 

On the contrary, I _have_ seen quite a few different resources suggest using `-q` (i.e. `--quiet`) to aid with silencing superfluous information, and that is in essence what the CLI already offers. 

I'm open to the idea of sending this info to stderr if enough support for the change is shown, or if you're able to provide any further context that would help me see it as an appropriate use of stderr, but at the moment I'm not convinced it's the right thing to do.

**Comment by joeshaw** [comment]
Closing this.  Totally reasonable difference in opinion as to whether non-error informational output should go to stdout or stderr.  Having the `--quiet`/`-q` option suppress that info is good enough for it to work.
