### ISSUE TITLE
Installation via homebrew results in 404

### ISSUE THREAD

**Issue by nakkamarra** [fastly/cli#781]
**Version**

N/A

**What happened**

Tried installing fastly cli by using the steps outlined by the link in the README but got a 404.

```
brew install fastly/tap/fastly

Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).

You have 34 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Fetching fastly/tap/fastly
==> Downloading https://github.com/fastly/cli/releases/download/v5.1.0/fastly_v5.1.0_darwin-amd64.tar.gz
curl: (22) The requested URL returned error: 404

Error: fastly: Failed to download resource "fastly"
Download failed: https://github.com/fastly/cli/releases/download/v5.1.0/fastly_v5.1.0_darwin-amd64.tar.gz
```

**Comment by Integralist** [comment]
👋🏻 Hi @nakkamarra 

Apologies! There was a failure in the Fastly CLI CI related to an issue with publishing to Arch Linux, which blocked us from completing the release process.

I managed to get the release published this morning:
https://github.com/fastly/cli/releases/tag/v5.1.0

If you try again with the Homebrew install you should find that it can now download the relevant artifact from GitHub.
