### ISSUE TITLE
SHA256 mismatch when installing via homebrew 

### ISSUE THREAD

**Issue by jwadolowski** [fastly/cli#782]
**Version**

`5.1.0`

**What happened**

```
$ brew install fastly/tap/fastly
fastly 5.0.0 is already installed but outdated (so it will be upgraded).
==> Fetching fastly/tap/fastly
==> Downloading https://github.com/fastly/cli/releases/download/v5.1.0/fastly_v5.1.0_darwin-amd64.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/238323615/7a03a263-e551-40e4-95bd-b6dc3bc54ab2?X-Amz-Algorithm=AWS4-HMAC-SHA256&
######################################################################## 100.0%
Error: fastly: SHA256 mismatch
Expected: 74976c85a6745dde5196de116f2744289bbcdc947d1015a98ef5bf8836cbf19e
  Actual: 76807dbf10c3ca09ee50beac36b1e524c74e82d81a5b325fa54e5c9e12cc8e68
    File: /Users/jwadolowski/Library/Caches/Homebrew/downloads/1c2417f00c7cab5494d4c28490c9ffbf1fd71f3976ad89e3221d069f94ba8c6f--fastly_v5.1.0_darwin-amd64.tar.gz
To retry an incomplete download, remove the file above.
```

Most likely related to #781. Removal of aforementioned `.tar.gz` file does not change much.

**Comment by Integralist** [comment]
👋🏻 

Thanks @jwadolowski I'll investigate and report back.

**Comment by Integralist** [comment]
👋🏻 

If you run `brew upgrade fastly/tap/fastly` this should hopefully now retrieve the [updated formula](https://github.com/fastly/homebrew-tap/commit/52e63d705b09b0aa3ecebf06065fe8030439adb2) which will contain the SHASUM hashes updated to align with the [GitHub release assets file](https://github.com/fastly/cli/releases/download/v5.1.0/fastly_v5.1.0_SHA256SUMS).

I'll close this issue for now but if there are still problems then just let me know. 

Thanks!

**Comment by Integralist** [comment]
Ah! OK great, thank you for that update @jwadolowski very much appreciated 👍🏻
