### ISSUE TITLE
Error downloading viceroy

### ISSUE THREAD

**Issue by gaastonsr** [fastly/cli#791]
**Version**

5.1.1

**What happened**

I'm trying to run `fastly compute serve` and I get the following error.

<img width="889" alt="Screenshot 2023-02-03 at 2 44 40 PM" src="https://user-images.githubusercontent.com/2997285/216707354-41f32a25-60d2-4358-a4de-51e44b7524d1.png">

My internet has been very slow today, do you think that could be related or can you confirm it's a current issue?

Thanks.

**Comment by fgsch** [comment]
Sounds like #289 . Can you check your DNS settings?

**Comment by gaastonsr** [comment]
I was connecting to an access point really far away from me and I was having spotty internet, connecting to the right network fixed it. Thanks!
