### ISSUE TITLE
unknown long flag '--skip-verification'

### ISSUE THREAD

**Issue by CGeorges** [fastly/cli#813]
**6.0.3**

Please paste the output of `fastly version` here.

ERROR: error parsing arguments: unknown long flag '--skip-verification'.

The flag is still mentioned in the documentation in the [examples section](https://developer.fastly.com/reference/cli/compute/build/). My Git actions were using `fastly/compute-actions/build@v2`, not until recently it was using `/opt/hostedtoolcache/fastly/5.0.0/x64/fastly version` but I see now it switched to `/opt/hostedtoolcache/fastly/6.0.3/x64/fastly version` where I assume this flag was removed. Maybe the github action version should have been incremented as well if we're switching to another major version of the CLI?

**Comment by Integralist** [comment]
Thanks @CGeorges for raising this issue.

I'm going to be opening a PR shortly to fix both the CLI 'examples' docs as well as remove the flag from the compute-actions repo. 

I'll also discuss with the team responsible for the compute-actions repo to see what they think about your suggestion regarding anchoring the compute-action repo to a major version of the CLI and bumping the action version when they bump the CLI version, as this makes a lot of sense to me 👍🏻

**Comment by CGeorges** [comment]
Thanks @Integralist 
I've just noticed it actually takes a parameter "cli_version" that we can use to lock out pipelines to a certain version. So my suggestion is probably irrelevant. :)

**Comment by Integralist** [comment]
Closing since I've merged https://github.com/fastly/cli/pull/816 (documentation should be updated on developer.fastly.com within the next 24hrs).
