### ISSUE TITLE
`fastly compute deploy` doesn't evaluate setup with newly created service

### ISSUE THREAD

**Issue by bsurmanski** [fastly/cli#821]
**Version**
Fastly CLI version v6.0.3 (752ef8f)
Built with go version go1.19.5 linux/amd64
Viceroy version: viceroy 0.2.12

**What happened**

when running the following command on a pre-built package .tar.gz:
`fastly compute deploy --token=<REDACTED> --package=<REDACTED>.tar.gz --verbose`

the command correctly turns up a service and deploys the package, but I would expect the starter-kit [setup] section of the fastly.toml to run.

I get the following output:
```
Fastly API token provided via --token
Fastly API endpoint: https://api.fastly.com

INFO: Using fastly.toml within --package archive: <REDACTED>.tar.gz

There is no Fastly service associated with this package. To connect to an existing service
add the Service ID to the fastly.toml file, otherwise follow the prompts to create a
service now.

Press ^C at any time to quit.

Create new service: [y/N] y

Service name: [] Test
Creating service...

Domain: [<REDACTED>.edgecompute.app] 

Backend (hostname or IP address, or leave blank to stop adding backends): 


INFO: Processing of the fastly.toml [setup] configuration happens only when there
is no existing service. Once a service is created, any further changes to the service or
its resources must be made manually.

Uploading package...
Activating version...

Manage this service at:
	https://manage.fastly.com/configure/services/<REDACTED>

View this service at:
	https://<REDACTED>.edgecompute.app


SUCCESS: Deployed package (service <REDACTED>, version 1)
```

Notably, there is this line: "INFO: Processing of the fastly.toml [setup] configuration happens only when there
is no existing service." Which sounds incorrect as the CLI *just* created the service (it did not exist before the command)

**Comment by Integralist** [comment]
Hi @bsurmanski 

Can I ask which starter kit you used and was there any changes made to the fastly.toml configuration file?

Thanks.

**Comment by bsurmanski** [comment]
It was one that I wrote myself. So, I suppose I modified it. I've removed a few entries, but my fastly.toml looks something like:

Here is what it looks like:
```
authors = ["test"]
description = "test project"
language = "rust"
manifest_version = 2
name = "test project"
service_id = ""

[setup]
  [setup.backends]
    [setup.backends.backend]
     description = "Content or application origin"

    [setup.dictionaries]
      [setup.dictionaries.config]
       [setup.dictionaries.config.items]
        [setup.dictionaries.recaptcha.items.backend_name]
         description = "Name matching the origin backend "
         value = "backend"
        [setup.dictionaries.recaptcha.items.log_level]
         description = "Verbosity of logs sent to logging endpoint (if set). One of [info, warn, error, debug, trace]."
         value = "info"

[scripts]
  build = "cargo build --bin test-project --release --target wasm32-wasi --color always"
```

notably, the [startup] section correctly activates on the same project when running `fastly compute publish` on the source directory of the package. Though, I am undergoing a review to open-source the package and wish to distribute the package pre-compiled before then. `fastly compute publish` doesn't seem to work on a precompile tar.gz package.

**Comment by bsurmanski** [comment]
The "configuration happens only when there is no existing service" message is printed here: https://github.com/fastly/cli/blob/17a06f6c1adcbd32087fd15b6f877a2e7059505c/pkg/commands/compute/deploy.go#L986

Should that condition read `!newService`?

**Comment by Integralist** [comment]
Hi @bsurmanski 

Thanks for your patience. This has been my first chance to revisit your issue.

I've used your configuration with the latest CLI release (`v8.0.1`) and the steps I've gone through were as follows...

1. `mkdir testing-fastly-cli && cd testing-fastly-cli`
2. `fastly compute init --language rust` (and I selected the 'default starter kit')
3. I manually modified the `fastly.toml` manifest to include your `[setup]` configuration
4. `fastly compute build` (which produces `pkg/testing-fastly-cli.tar.gz`)
5. `fastly compute deploy --package pkg/testing-fastly-cli.tar.gz --verbose`

As you can see from the following screenshot I was able to successfully deploy the application and was also prompted as per the `[setup]` configuration that I copied from your earlier example...

<img width="958" alt="Screenshot 2023-03-15 at 17 14 54" src="https://user-images.githubusercontent.com/180050/225388520-776818f9-1ae7-4e9e-9e60-150a9a800156.png">

I don't think there have been any fundamental changes recently to the CLI that would cause the `[setup]` configuration to not be processed via the `compute deploy` subcommand, but maybe run `fastly update` to get the latest release just in case this helps.

**Comment by Integralist** [comment]
As I'm unable to replicate the issue using your `[setup]` configuration with the latest CLI release, I'm going to close off this issue for now. Please do continue the conversation/re-open if with the latest CLI you're still experiencing a problem or you have more context that would assist us in replicating the problem. Thanks!
