### ISSUE TITLE
ObjectStore date information is wrong

### ISSUE THREAD

**Issue by marlun78** [fastly/cli#868]
**Version**

```
Fastly CLI version v8.0.0 (10b5dbe)
Built with go version go1.20.1 linux/amd64
Viceroy version: viceroy 0.3.5
```

**What happened**

The date information (`Created (UTC)` and `Last edited (UTC)`) you get in response from running the `object-store list`-command are always the "now" date-time. So every new minute you re-run the command, you get new date information. 

```
fastly object-store list
```

**Example response 1**
```
ID: gxjqiwlgmomcdip1o0oacl
Name: test-store
Created (UTC): 2023-03-15 14:25
Last edited (UTC): 2023-03-15 14:25
```

...a few minutes later...

**Example response 2**
```
ID: gxjqiwlgmomcdip1o0oacl
Name: test-store
Created (UTC): 2023-03-15 14:29
Last edited (UTC): 2023-03-15 14:29
```

**Comment by Integralist** [comment]
Thanks, @marlun78 for raising this issue. It looks to be with the API itself rather than the CLI.

If you run the following curl command you should see the same behaviour...

```
curl -s "https://api.fastly.com/resources/stores/object" -H "Fastly-Key: $FASTLY_API_TOKEN" -H "Accept: application/json"
```

I've reached out to the relevant team internally to investigate.

**Comment by Integralist** [comment]
I've had an update from the team to say they've identified the issue and are actively working on a solution.

**Comment by marlun78** [comment]
Great, thanks!
