### ISSUE TITLE
fastly deploy at 8.1.2 503 

### ISSUE THREAD

**Issue by kukuhome1** [fastly/cli#885]
**Version**
8.1.2
Please paste the output of `fastly version` here.

**What happened**
i try to run 
fastly compute deploy
**ERROR: the Fastly API returned 503 Service Unavailable: .**
Please describe the command you ran, what you expected to happen, and what happened instead.

**Comment by kukuhome1** [comment]
ignore

**Comment by Integralist** [comment]
👋🏻 Sounds like from your last comment that this is no longer an issue so I'm going to close off this ticket. Please feel free to re-open/comment further if you have any other problems 👍🏻
