### ISSUE TITLE
Invalid local_server configuration causes an error that is not displayed unless using --verbose

### ISSUE THREAD

**Issue by tedmielczarek-fastly** [fastly/cli#913]
**Version**

Fastly CLI version v8.2.4 (8547a97)
Built with go version go1.20.2 linux/amd64
Viceroy version: viceroy 0.4.5

**What happened**

I was attempting to run my service locally using `fastly compute serve` after having made some changes to use a secret store, and configuring `[local_server.secret_stores]` in my `fastly.toml`. The documentation for  the schema is incorrect (it says to use `path` but actually wants `file`), so an error occurred, but the error isn't printed:

```
% fastly compute serve --skip-build
✓ Running local server

INFO: Listening on http://127.0.0.1:7676

INFO: Command output:
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

ERROR: error during execution process (see 'command output' above): exit status 1.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

Running with `--verbose` does show the underlying error:

```
% fastly compute serve --skip-build --verbose
Fastly API token provided via config file (profile: a3f)
Fastly API endpoint: https://api.fastly.com

✓ Running local server

Manifest: <…>/fastly.toml
Wasm binary: bin/main.wasm
Viceroy binary: /Users/ted/Library/Application Support/fastly/viceroy
Viceroy version: viceroy 0.4.5

INFO: Command output:
--------------------------------------------------------------------------------
2023-04-18T15:48:44.386254Z ERROR invalid configuration for 'secrets': The `file` or `data` key for the object `encryption_key` is not set. One must be used.
--------------------------------------------------------------------------------

ERROR: error during execution process (see 'command output' above): exit status 1.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

**Comment by Integralist** [comment]
👋🏻 

So to clarify why the error doesn't show up within `--verbose`:

Viceroy recently changed its behaviour such that displaying errors only happens behind a `--verbose` flag.

The Fastly CLI doesn't pass the `--verbose` flag to Viceroy unless `--verbose` is set on the Fastly CLI command you're executing.

It might be worth the Fastly CLI always setting the `--verbose` flag when invoking Viceroy so that errors are reported without having to know about setting the `--verbose` flag.
