### ISSUE TITLE
Unable to reactivate deactivated deployment

### ISSUE THREAD

**Issue by ephemer** [fastly/cli#917]
**Version**

> $ fastly version
> Fastly CLI version v9.0.0 (45adb71a)
> Built with go version go1.20.3 linux/amd64
> Viceroy version: viceroy 0.2.4

**What happened**

```
fastly compute publish
✓ Verifying fastly.toml
✓ Identifying package name
✓ Identifying toolchain
✓ Running [scripts.build]
✓ Creating package archive

SUCCESS: Built package (pkg/[The-Package].tar.gz)

✗ Uploading package

ERROR: the Fastly API returned 404 Not Found: Not found.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

Our deployment ID is `5EC316PAgFoY1PKOlnagis`

**Comment by Integralist** [comment]
Hi @ephemer 

Thanks for opening this issue.

Can you let me know if you have access to a Fastly Customer Support Slack channel? As it can be easier to chat there if you do have access (no worries if you don't).

So unfortunately the Fastly API response error is a bit ambiguous here 🤔

You mention in the title of this issue that the service is 'deactivated'. I'm going to email you separately the details.

You can run the following Fastly CLI command to 'activate' a service, so something like this should help before trying to run `fastly compute publish` again...

```shell
 fastly service-version activate --service-id 5EC316PAgFoY1PKOlnagis  --version=<VERSION>
```

Documentation: https://developer.fastly.com/reference/cli/service-version/activate/

Thanks!

**Comment by Integralist** [comment]
I'm going to close this issue for now, but if you have any other problems then feel free to either open another issue (or re-open this one if it's relevant), or you can drop an email to support@fastly.com 

Thanks!

**Comment by ephemer** [comment]
Thanks @Integralist but that doesn't help:

```
fastly service-version activate --service-id 5EC316PAgFoY1PKOlnagis  --version=2 --autoclone

ERROR: the Fastly API returned 400 Bad Request: Bad request (ERROR: Wasm service has no package).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

**Comment by ephemer** [comment]
```
$ fastly compute update --version latest
✗ Uploading package

ERROR: error uploading package: 404 - Not Found:

    Title:  Not found.

Run `fastly compute build` to produce a Compute@Edge package, alternatively use the --package flag to reference a package outside of the current project.


$ fastly compute build
✓ Verifying fastly.toml
✓ Identifying package name
✓ Identifying toolchain
✓ Running [scripts.build]
✓ Creating package archive

SUCCESS: Built package (pkg/Apollo-Server-Wasm.tar.gz)


$ fastly compute update --version latest
✗ Uploading package

ERROR: error uploading package: 404 - Not Found:

    Title:  Not found.

Run `fastly compute build` to produce a Compute@Edge package, alternatively use the --package flag to reference a package outside of the current project.
```

Nothing is possible right now. It's likely a problem with the account rather than with the CLI, but my request with Support is not progressing either
