### ISSUE TITLE
[FEATURE REQUEST] Create a new folder on fastly compute init

### ISSUE THREAD

**Issue by JonathanSpeek** [fastly/cli#933]
**Is your feature request related to a problem? Please describe.**
Many CLI's, when creating or init-ing a new project will create the directory for you. Would be great to have that as default so I don't have to 
```bash
mkdir project-name
cd project-name
fastly compute init
```
<img width="1089" alt="image" src="https://github.com/fastly/Viceroy/assets/11696256/4764f5be-369c-4fcf-8dab-ed34482be570">

**Describe the solution you'd like**
Ideally it'd create a new directory using the project name it prompts for:
![CleanShot 2023-05-12 at 12 00 12@2x](https://github.com/fastly/Viceroy/assets/11696256/60e5ba4f-e206-4978-bf69-b4df7c416478)

**Describe alternatives you've considered**
Manually creating a new directory every time.

**Comment by Integralist** [comment]
👋🏻 Thanks for opening this issue.

I like this idea so I'll create an internal ticket to track the work.

**Comment by JonathanSpeek** [comment]
Given this would be a tradeoff that would require current users to learn a different flow, I'm going to close-out this request. Thanks!
