### ISSUE TITLE
`fastly_http_req::redirect_to_grip_proxy` has not been defined

### ISSUE THREAD

**Issue by jamesarosen** [fastly/cli#963]
**Version**

```
; fastly version
Fastly CLI version v10.2.1 (308752a2)
Built with go version go1.20.5 linux/amd64
Viceroy version: viceroy 0.5.1
```

**What happened**

I ran `fastly compute deploy`, then answered the questions. The end of the output:

```
Backend (hostname or IP address, or leave blank to stop adding backends):

✓ Creating domain '<redacted domain name>'
✓ Uploading package
✗ Activating service (version 1)

INFO: Cleaning up service

INFO: Removing Service ID from fastly.toml
Cleanup complete

ERROR: the Fastly API returned 400 Bad Request: Bad request (ERROR: unknown import: `fastly_http_req::redirect_to_grip_proxy` has not been defined).
```

Note: I have a custom `fastly.api_endpoint` in my `~/.../fastly/config.toml`.

**Comment by Integralist** [comment]
👋🏻 Hi @jamesarosen 

That error doesn't look to be directly related to the CLI.

The error response from the API mentioned `fastly_http_req::redirect_to_grip_proxy` which is similar to an error that was related to Viceroy ([see here](https://github.com/fastly/Viceroy/issues/110)) but as you weren't running `compute serve` (which is what passes your application code to Viceroy) then something in the API itself is having problems handling whatever your application code is using.

As you work at Fastly, I've pinged you internally to discuss this further and I've also suggested different teams you might be able to reach out to. For now, I'm going to close this issue as this doesn't look to be related to the CLI itself (from what I can tell).
