### ISSUE TITLE
Service describe command by name doesn't work for our services created after increasing the limit

### ISSUE THREAD

**Issue by yasuota** [fastly/cli#974]
## **Version**

Please paste the output of `fastly version` here.

```
Fastly CLI version v10.2.2 (839d1fcb)
Built with go version go1.20.5 linux/amd64
```

## **What happened**

(1) 

After I had Fastly support increase the limit of our service from 100 to 200 and created some new services (No. 101, No. 102, No. 103…), I got the below error for those new services when running the [service describe command](https://developer.fastly.com/reference/cli/service/describe/). 

(I don’t see it for our services created before having them increase the limit.)

Command I ran

```
❯ fastly service describe --service-name ${ServiceName} >/dev/null 

ERROR: error matching service name with available services.

If you believe this error is the result of a bug, please file an
issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md

```

(2) 
Having checked the repository, this error occurs at the below line. 

https://github.com/fastly/cli/blob/ee76902fa429ef996845a88cfa834116b667d008/pkg/cmd/flags.go#L156C3-L167C2

## Please describe the command you ran, what you expected to happen, and what happened instead.

(A) 
However, when I use the command by Service ID like this, it works fine.

```
❯ fastly service describe --service-id ${ServiceID}
```

(B) 
Additionally, when it comes to these equivalent APIs, it works fine.

[List Services](https://developer.fastly.com/reference/api/services/service/#list-services)

```
curl -sH "Fastly-Key: {secret}" "https://api.fastly.com/service?page=2" | jq ". | length"
```
FYI : The target service was included at Page2. Therefore, I wonder if this issue could be related to page rotation because the new services are affected.

[Search Service by Name](https://developer.fastly.com/reference/api/services/service/#search-service)
```
curl -sH "Fastly-Key: {secret}" "https://api.fastly.com/service/search?name=$servicename" | jq . | head -10
```

(C) 
In Fastly support side, they said the problematic command works fine for our services.
Also, their cli version is the same as mine.

**Comment by chiyoppy** [comment]
I have same problem. Once this bug is fixed, I won't have to manually purge the cache.

**Comment by Integralist** [comment]
👋🏻 Thanks @yasuota for opening this issue.

Looks like the source of the bug is the `ListServices` call is to an API endpoint that includes pagination and yet we're not iterating through all available pages, just the initial result.

I'll open an internal ticket and get this scheduled to be fixed ASAP.

Thanks!

**Comment by Integralist** [comment]
https://github.com/fastly/cli/releases/tag/v10.2.3
