### ISSUE TITLE
KV: ERROR: the Fastly API returned 503 Service Unavailable: error at index: 0.

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [fastly/cli#989]
**Version**
```
Fastly CLI version v10.2.4 (3906b08)
Built with go version go1.20.6 linux/amd64
```

**What happened**

Unable to work with KV, example:
```
devshell-env ❯ fastly kv-store create --name=AAA

ERROR: the Fastly API returned 503 Service Unavailable: error at index: 0.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```
I was able to create and assign KV through the website but it throws an error when trying to access it

**Comment by Integralist** [comment]
Hi @gytis-ivaskevicius 

This looks to work for me using the same CLI version...

<img width="497" alt="Screenshot 2023-08-04 at 11 51 15" src="https://github.com/fastly/cli/assets/180050/6a0c22f2-7640-4a8d-a9a1-55d20c574297">

I'm thinking maybe you need access to KV Store to be added to your account.

Please reach out to support@fastly.com with your Customer ID and they should be able to help.

Thanks!
